export CONFIG_ZCFG_BE_MODULE_DSL
ifeq ($(CONFIG_ZCFG_BE_MODULE_DSL),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_DSL
endif

export CONFIG_ZCFG_BE_MODULE_ATM_LINK
ifeq ($(CONFIG_ZCFG_BE_MODULE_ATM_LINK),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ATM_LINK
endif

export CONFIG_ZCFG_BE_MODULE_PTM_LINK
ifeq ($(CONFIG_ZCFG_BE_MODULE_PTM_LINK),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_PTM_LINK
endif

export CONFIG_ZCFG_BE_MODULE_DATA_USAGE
ifeq ($(CONFIG_ZCFG_BE_MODULE_DATA_USAGE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_DATA_USAGE
endif

export CONFIG_ZCFG_BE_MODULE_DEVINFO
ifeq ($(CONFIG_ZCFG_BE_MODULE_DEVINFO),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_DEVINFO
endif

export CONFIG_ZCFG_BE_MODULE_OPTICAL
ifeq ($(CONFIG_ZCFG_BE_MODULE_OPTICAL),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_OPTICAL
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_XPON
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_XPON),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_XPON
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_GPON
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_GPON),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_GPON
endif

export CONFIG_ZCFG_BE_MODULE_END_POINT
ifeq ($(CONFIG_ZCFG_BE_MODULE_END_POINT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_END_POINT
endif

export CONFIG_ZCFG_BE_MODULE_SMART_CARD
ifeq ($(CONFIG_ZCFG_BE_MODULE_SMART_CARD),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_SMART_CARD
endif

export CONFIG_ZCFG_BE_MODULE_BULK_DATA
ifeq ($(CONFIG_ZCFG_BE_MODULE_BULK_DATA),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_BULK_DATA
endif

export CONFIG_ZCFG_BE_MODULE_HPNA
ifeq ($(CONFIG_ZCFG_BE_MODULE_HPNA),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_HPNA
endif

export CONFIG_ZCFG_BE_MODULE_HOMEPLUG
ifeq ($(CONFIG_ZCFG_BE_MODULE_HOMEPLUG),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_HOMEPLUG
endif

export CONFIG_ZCFG_BE_MODULE_GHN
ifeq ($(CONFIG_ZCFG_BE_MODULE_GHN),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_GHN
endif

export CONFIG_ZCFG_BE_MODULE_UPA
ifeq ($(CONFIG_ZCFG_BE_MODULE_UPA),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_UPA
endif

export CONFIG_ZCFG_BE_MODULE_MOCA
ifeq ($(CONFIG_ZCFG_BE_MODULE_MOCA),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_MOCA
endif

export CONFIG_ZCFG_BE_MODULE_PERIODIC_STATISTICS
ifeq ($(CONFIG_ZCFG_BE_MODULE_PERIODIC_STATISTICS),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_PERIODIC_STATISTICS
endif

export CONFIG_ZCFG_BE_MODULE_FAULT_MGMT
ifeq ($(CONFIG_ZCFG_BE_MODULE_FAULT_MGMT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_FAULT_MGMT
endif

export CONFIG_ZCFG_BE_MODULE_FAP
ifeq ($(CONFIG_ZCFG_BE_MODULE_FAP),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_FAP
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_LOOPGUARD
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_LOOPGUARD),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_LOOPGUARD
endif

export CONFIG_ZCFG_BE_MODULE_USB
ifeq ($(CONFIG_ZCFG_BE_MODULE_USB),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_USB
endif

export CONFIG_ZCFG_BE_MODULE_WIFI
ifeq ($(CONFIG_ZCFG_BE_MODULE_WIFI),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_WIFI
endif

export CONFIG_ZCFG_BE_MODULE_BRIDGE_VLAN_COUNTER
ifeq ($(CONFIG_ZCFG_BE_MODULE_BRIDGE_VLAN_COUNTER),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_BRIDGE_VLAN_COUNTER
endif

export CONFIG_ZCFG_BE_MODULE_GRE_TUNNEL
ifeq ($(CONFIG_ZCFG_BE_MODULE_GRE_TUNNEL),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_GRE_TUNNEL
endif

export CONFIG_ZCFG_BE_MODULE_GRE_TUNNEL_IFACE
ifeq ($(CONFIG_ZCFG_BE_MODULE_GRE_TUNNEL_IFACE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_GRE_TUNNEL_IFACE
endif

export CONFIG_ZCFG_BE_MODULE_RADV_INTFSET_OPT
ifeq ($(CONFIG_ZCFG_BE_MODULE_RADV_INTFSET_OPT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_RADV_INTFSET_OPT
endif

export CONFIG_ZCFG_BE_MODULE_GATEWAY_INFO
ifeq ($(CONFIG_ZCFG_BE_MODULE_GATEWAY_INFO),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_GATEWAY_INFO
endif

export CONFIG_ZCFG_BE_MODULE_DNS_RELAY
ifeq ($(CONFIG_ZCFG_BE_MODULE_DNS_RELAY),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_DNS_RELAY
endif

export CONFIG_ZCFG_BE_MODULE_NAT_PORT_CTRL
ifeq ($(CONFIG_ZCFG_BE_MODULE_NAT_PORT_CTRL),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_NAT_PORT_CTRL
endif

export CONFIG_ZCFG_BE_MODULE_NEIGHBOR_DISCOVERY_INTFSET
ifeq ($(CONFIG_ZCFG_BE_MODULE_NEIGHBOR_DISCOVERY_INTFSET),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_NEIGHBOR_DISCOVERY_INTFSET
endif

export CONFIG_ZCFG_BE_MODULE_SNMP
ifeq ($(CONFIG_ZCFG_BE_MODULE_SNMP),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_SNMP
endif

export CONFIG_ZCFG_BE_MODULE_VC_AUTO_HUNT
ifeq ($(CONFIG_ZCFG_BE_MODULE_VC_AUTO_HUNT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_VC_AUTO_HUNT
endif

export CONFIG_ZCFG_BE_MODULE_UPNP
ifeq ($(CONFIG_ZCFG_BE_MODULE_UPNP),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_UPNP
endif

export CONFIG_ZCFG_BE_MODULE_STB_VENDOR_ID
ifeq ($(CONFIG_ZCFG_BE_MODULE_STB_VENDOR_ID),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_STB_VENDOR_ID
endif

export CONFIG_ZCFG_BE_MODULE_WLAN_SCHEDULER
ifeq ($(CONFIG_ZCFG_BE_MODULE_WLAN_SCHEDULER),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_WLAN_SCHEDULER
endif

export CONFIG_ZCFG_BE_MODULE_WWAN_BACKUP
ifeq ($(CONFIG_ZCFG_BE_MODULE_WWAN_BACKUP),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_WWAN_BACKUP
endif

export CONFIG_ZCFG_BE_MODULE_SAMBA
ifeq ($(CONFIG_ZCFG_BE_MODULE_SAMBA),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_SAMBA
endif

export CONFIG_ZCFG_BE_MODULE_VOICE
ifeq ($(CONFIG_ZCFG_BE_MODULE_VOICE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_VOICE
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_PHONE_DECT
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_PHONE_DECT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_PHONE_DECT
endif

export CONFIG_ZCFG_BE_MODULE_DLNA
ifeq ($(CONFIG_ZCFG_BE_MODULE_DLNA),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_DLNA
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_VLAN_GROUP
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_VLAN_GROUP),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_VLAN_GROUP
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_IPP_CONFIG
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_IPP_CONFIG),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_IPP_CONFIG
endif

export CONFIG_ZCFG_BE_MODULE_TFTP_SERVER_NAME
ifeq ($(CONFIG_ZCFG_BE_MODULE_TFTP_SERVER_NAME),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_TFTP_SERVER_NAME
endif

export CONFIG_ZCFG_BE_MODULE_SPEED_TEST
ifeq ($(CONFIG_ZCFG_BE_MODULE_SPEED_TEST),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_SPEED_TEST
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_ONECONNECT
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_ONECONNECT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_ONECONNECT
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_ONECONNECT_PARENTAL_CTRL
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_ONECONNECT_PARENTAL_CTRL),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_ONECONNECT_PARENTAL_CTRL
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_POWER_MANAGEMENT
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_POWER_MANAGEMENT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_POWER_MANAGEMENT
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_SFP_POWER_MGMT
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_SFP_POWER_MGMT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_SFP_POWER_MGMT
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_AP_STEERING
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_AP_STEERING),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_AP_STEERING
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_EASYMESH
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_EASYMESH),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_EASYMESH
endif

export CONFIG_ZCFG_BE_MODULE_WPS_BTN_PRESS
ifeq ($(CONFIG_ZCFG_BE_MODULE_WPS_BTN_PRESS),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_WPS_BTN_PRESS
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_ONESSID
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_ONESSID),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_ONESSID
endif

export CONFIG_ZCFG_BE_MODULE_PROXIMITY_SENSOR
ifeq ($(CONFIG_ZCFG_BE_MODULE_PROXIMITY_SENSOR),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_PROXIMITY_SENSOR
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_CELLWAN
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_CELLWAN),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_CELLWAN
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_LIFEMOTE
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_LIFEMOTE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_LIFEMOTE
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_QUANTWIFI
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_QUANTWIFI),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_QUANTWIFI
endif

export CONFIG_ZCFG_BE_MODULE_PKT_CAPTURE
ifeq ($(CONFIG_ZCFG_BE_MODULE_PKT_CAPTURE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_PKT_CAPTURE
endif

export CONFIG_ZCFG_BE_MODULE_OAAAA_CUSTOMIZATION
ifeq ($(CONFIG_ZCFG_BE_MODULE_OAAAA_CUSTOMIZATION),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_OAAAA_CUSTOMIZATION
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_PPTP_SUPPORT
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_PPTP_SUPPORT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_PPTP_SUPPORT
endif

export CONFIG_ZCFG_BE_MODULE_GPON_INFO
ifeq ($(CONFIG_ZCFG_BE_MODULE_GPON_INFO),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_GPON_INFO
endif

export CONFIG_ZCFG_BE_MODULE_IPK_PACKAGE
ifeq ($(CONFIG_ZCFG_BE_MODULE_IPK_PACKAGE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_IPK_PACKAGE
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_BANDWIDTH_IMPROVEMENT
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_BANDWIDTH_IMPROVEMENT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_BANDWIDTH_IMPROVEMENT
endif

export CONFIG_ZCFG_BE_MODULE_ZLOG_USE_DEBUG
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZLOG_USE_DEBUG),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZLOG_USE_DEBUG
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_URL_FILTER
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_URL_FILTER),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_URL_FILTER
endif

export CONFIG_ZCFG_BE_MODULE_CYBER_SECURITY
ifeq ($(CONFIG_ZCFG_BE_MODULE_CYBER_SECURITY),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_CYBER_SECURITY
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_LICENSE
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_LICENSE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_LICENSE
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_MODSW_ZYEE
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_MODSW_ZYEE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_MODSW_ZYEE
endif

export CONFIG_ZCFG_BE_MODULE_MOS_USER_CONFIG
ifeq ($(CONFIG_ZCFG_BE_MODULE_MOS_USER_CONFIG),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_MOS_USER_CONFIG
endif

export CONFIG_ZCFG_BE_MODULE_IPSEC_VPN
ifeq ($(CONFIG_ZCFG_BE_MODULE_IPSEC_VPN),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_IPSEC_VPN
endif

export CONFIG_ZCFG_BE_MODULE_VPN_CLIENT
ifeq ($(CONFIG_ZCFG_BE_MODULE_VPN_CLIENT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_VPN_CLIENT
endif

export CONFIG_ZCFG_BE_MODULE_XMPP
ifeq ($(CONFIG_ZCFG_BE_MODULE_XMPP),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_XMPP
endif

export CONFIG_ZCFG_BE_MODULE_WIFI_REPEATER
ifeq ($(CONFIG_ZCFG_BE_MODULE_WIFI_REPEATER),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_WIFI_REPEATER
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_OPERATION_MODE
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_OPERATION_MODE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_OPERATION_MODE
endif

export CONFIG_ZCFG_BE_MODULE_MULTIPLE_CONFIG
ifeq ($(CONFIG_ZCFG_BE_MODULE_MULTIPLE_CONFIG),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_MULTIPLE_CONFIG
endif

export CONFIG_ZCFG_BE_MODULE_DSL_TROUBLE_SHOOTING
ifeq ($(CONFIG_ZCFG_BE_MODULE_DSL_TROUBLE_SHOOTING),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_DSL_TROUBLE_SHOOTING
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_REBOOT_SCHEDULE
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_REBOOT_SCHEDULE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_REBOOT_SCHEDULE
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_NAND_DUMP
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_NAND_DUMP),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_NAND_DUMP
endif

export CONFIG_ZCFG_BE_MODULE_ZYXEL_MULTI_WAN
ifeq ($(CONFIG_ZCFG_BE_MODULE_ZYXEL_MULTI_WAN),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_ZYXEL_MULTI_WAN
endif

export CONFIG_ZCFG_BE_MODULE_QOS
ifeq ($(CONFIG_ZCFG_BE_MODULE_QOS),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_QOS
endif

### feature ext ###
ifeq ($(CONFIG_ZCFG_BE_5G_EXTENSION),y)
export CONFIG_ZCFG_BE_5G_EXTENSION
endif

# debug extension
ifeq ($(CONFIG_ZCFG_BE_DEBUG_EXTENSION),y)
export CONFIG_ZCFG_BE_DEBUG_EXTENSION

export CONFIG_ZCFG_BE_MODULE_DEBUG_ZLOG_WITH_ZCONSOLE
ifeq ($(CONFIG_ZCFG_BE_MODULE_DEBUG_ZLOG_WITH_ZCONSOLE),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_DEBUG_ZLOG_WITH_ZCONSOLE
endif

export CONFIG_ZCFG_BE_MODULE_DEBUG_GW_PING_FAIL_LOG
ifeq ($(CONFIG_ZCFG_BE_MODULE_DEBUG_GW_PING_FAIL_LOG),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_DEBUG_GW_PING_FAIL_LOG
endif

endif # end of CONFIG_ZCFG_BE_DEBUG_EXTENSION


ifeq ($(CONFIG_ZCFG_BE_SAMPLE_EXTENSION),y)
export CONFIG_ZCFG_BE_SAMPLE_EXTENSION

export CONFIG_ZCFG_BE_MODULE_SAMPLE_ZYXEL_TEST
ifeq ($(CONFIG_ZCFG_BE_MODULE_SAMPLE_ZYXEL_TEST),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_SAMPLE_ZYXEL_TEST
endif

export CONFIG_ZCFG_BE_MODULE_SAMPLE_ONECONNECT
ifeq ($(CONFIG_ZCFG_BE_MODULE_SAMPLE_ONECONNECT),y)
ZFLAGS += -DCONFIG_ZCFG_BE_MODULE_SAMPLE_ONECONNECT
endif

export CONFIG_ZCFG_BE_LIB_SAMPLE_COMMON_LIB
ifeq ($(CONFIG_ZCFG_BE_LIB_SAMPLE_COMMON_LIB),y)
ZFLAGS += -DCONFIG_ZCFG_BE_LIB_SAMPLE_COMMON_LIB
endif

endif # endif CONFIG_ZCFG_BE_SAMPLE_EXTENSION

### end of feature ext ###
