#
# Copyright (C) 2006-2010 OpenWrt.org
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

ifneq ($(__zyxel_rules_inc),1)
__zyxel_rules_inc=1

#
#   CP, 2018-01-08 13:48:29
#
#   link all files in the folder and sub-folders to the destination
#       parameter 1 is the source directory
#       parameter 2 is the destination directory
#
define link_files
	for src_dir in `find $(1) -type d -print`; do \
	( \
		if [[ $$src_dir != "." ]]; \
		then \
			mkdir -p $(2)/$$src_dir; \
			for src_file in `find $$src_dir -maxdepth 1 -type f -print`; do \
			( \
				ln -f $$src_file $2/$$src_dir; \
			); \
			done \
		fi \
	); \
	done
endef

CP_AF:=cp -af

########################################################################
###    export some MACROs for toolchain
########################################################################
export TOOLCHAIN_DIR TOOLCHAIN_ROOT_DIR KERNEL_TOOLCHAIN_ROOT_DIR
export REAL_GNU_TARGET_NAME KERNEL_TOOLCHAIN_REAL_GNU_TARGET_NAME
export TOOLCHAIN_INC_DIRS TOOLCHAIN_LIB_DIRS
export CONFIG_EXTERNAL_TOOLCHAIN CONFIG_EXTERNAL_KERNEL_TOOLCHAIN
export KERNEL_TOOLCHAIN_INC_DIRS KERNEL_TOOLCHAIN_LIB_DIRS

########################################################################
###    export some MACROs for release GPL
########################################################################
export ZYXEL_PUBLIC_PACKAGE := $(TOPDIR)/package/public-zyxel
export ZYXEL_PRIVATE_PACKAGE:= $(TOPDIR)/package/private/zyxel

########################################################################
###    export some MACROs for packages
########################################################################
export CONFIG_ZYXEL_RMA_FW_SUPPORT CONFIG_ZYXEL_SYS_FWUR_SUPPORT
export CONFIG_ZYXEL_FIRMWARE_VERSION CONFIG_MRD_MODEL_ID
########################################################################
###    init
########################################################################
#store Zyxel common cflags
ZYXEL_COMMON_CFLAGS:=

#specific for userspace "process" and inherit the setting in ZYXEL_COMMON_CFLAGS
ZYXEL_APP_CFLAGS:=
ZYXEL_APP_LDFLAGS:=

#specific for userspace "libraries" and inherit the setting in ZYXEL_COMMON_CFLAGS
ZYXEL_LIB_CFLAGS:=
ZYXEL_LIB_LDFLAGS:=


########################################################################
###    START: Zyxel common compile flags
########################################################################
ZYXEL=y
ZYXEL_RSA_FORMAT=y

###########CROSS_PLATFORM###############################################
ifeq ($(CONFIG_TARGET_brcm963xx),y)
	ZCFG_PLATFORM=BROADCOM
endif
ifeq ($(CONFIG_TARGET_en75xx),y)
	ZCFG_PLATFORM=ECONET
endif
ifeq ($(CONFIG_TARGET_ramips)$,y)
	ZCFG_PLATFORM=MTKSOC
endif

ifeq ($(CONFIG_TARGET_mediatek),y)
	ZCFG_PLATFORM=MTK
endif

ZCFG_PLATFORM?=UNKNOW
export ZCFG_PLATFORM

########################################################################
# Broadcom Related
########################################################################
ifeq ("$(strip ${ZCFG_PLATFORM})","BROADCOM")

######Original define in target/linux/brcm963xx/*/target.mk#############
##### for inculding make.common BCM SDK define ######
########### Add CONFIG_BUILD_MSTC_VOICE_KSOCKET_RTP compile flag for VoIP related feature(Kernel Socket) ###########
export BRCM_BOARD=bcm963xx
export BRCM_CHIP=$(CONFIG_BRCMSDK$(shell echo $(CONFIG_BRCM_SDK_VERSION))_BRCM_CHIP)
export BRCM_CHIP_REV=$(CONFIG_BRCMSDK$(shell echo $(CONFIG_BRCM_SDK_VERSION))_BRCM_CHIP_REV)

export BCM_PROFILE=$(shell echo $(SUBTARGET) | tr a-z A-Z)
export BCM_BUILD_DIR=$(BUILD_DIR)/broadcom-sdk-$(call qstrip,$(CONFIG_BRCM_SDK_VERSION))$(call qstrip,$(CONFIG_BRCM_SDK_PATCH_VERSION))
export BCM_HOSTTOOLS_DIR=$(STAGING_DIR_HOST)/bin/$(shell echo $(CONFIG_BRCM_SDK_VERSION))

export BRCM_SDK_VERSION=$(strip $(shell echo $(CONFIG_BRCM_SDK_VERSION)))

export BCM_INSTALL_DIR=$(BCM_BUILD_DIR)/targets/$(BCM_PROFILE)/fs.install
export BRCMDRIVERS_DIR=$(BCM_BUILD_DIR)/bcmdrivers
export SHARED_DIR=$(BCM_BUILD_DIR)/shared
export INC_BRCMDRIVER_PUB_PATH=$(BRCMDRIVERS_DIR)/opensource/include
export INC_BRCMDRIVER_PRIV_PATH=$(BRCMDRIVERS_DIR)/broadcom/include
export INC_BRCMSHARED_PUB_PATH=$(SHARED_DIR)/opensource/include
export INC_BRCMSHARED_PRIV_PATH=$(SHARED_DIR)/broadcom/include

export CONFIG_BUILD_MSTC_VOICE_KSOCKET_RTP

ifeq ($(CONFIG_BRCMSDK$(shell echo $(CONFIG_BRCM_SDK_VERSION))_BUILD_UBOOT),y)
export BROADCOM_UBOOT_PLATFORM=y
ZYXEL_COMMON_CFLAGS += -DBROADCOM_UBOOT_PLATFORM
endif

ifeq ($(CONFIG_ZYXEL_FEATURE_BITS),y)
export ZYXEL_FEATURE_BITS=y
endif
ifeq ($(CONFIG_SAME_FW_FOR_PROJECTS),y)
export SAME_FW_FOR_PROJECTS=y
endif
ifeq ($(CONFIG_ZYXEL_DISABLE_TXRX_FOR_WAN_ACT),y)
export ZYXEL_DISABLE_TXRX_FOR_WAN_ACT=y
endif

# Change HW_LED to software control.(ex DX5601-B0_WIND) (WAN)
ifeq ($(CONFIG_ZYXEL_SUPPORT_SW_CTL_WAN_LED),y)
export ZYXEL_SUPPORT_SW_CTL_WAN_LED=y
endif

# Support software control lan aggregate led(ex. VMG8825-B50B)
ifeq ($(CONFIG_ZYXEL_SUPPORT_SW_LAN_AGGREGATE_LED),y)
export ZYXEL_SUPPORT_SW_LAN_AGGREGATE_LED=y
endif
# Support software control lan aggregate led(ex. VMG8825-B50B)
ifeq ($(CONFIG_ZYXEL_SUPPORT_SW_LAN_AGGREGATE_LED),y)
export ZYXEL_SUPPORT_SW_LAN_AGGREGATE_LED=y
endif
# VMG8825-B50B WIND, support 256MB and 512MB flash
ifeq ($(CONFIG_ZYXEL_SUPPORT_BOTH_256_512_FLASH),y)
export ZYXEL_SUPPORT_BOTH_256_512_FLASH=y
endif
#__ZyXEL__, for ZyXEL hardware depend misc.
ifeq ($(CONFIG_ZYXEL_QTN_WIFI_5G_SUPPORT),y)
export ZYXEL_QTN_WIFI_5G_SUPPORT=y
endif
ifeq ($(CONFIG_ZYXEL_QTN_SW_RESET),y)
export ZYXEL_QTN_SW_RESET=y
endif
ifeq ($(CONFIG_ZYXEL_SW_RESET_WIFI_MODULE),y)
export ZYXEL_SW_RESET_WIFI_MODULE=y
endif
ifeq ($(CONFIG_ZYXEL_WPS_SPOTLIGHT),y)
export ZYXEL_WPS_SPOTLIGHT=y
ifeq ($(CONFIG_ZYXEL_WPS_SPOTLIGHT_2GPIO),y)
export ZYXEL_WPS_SPOTLIGHT_2GPIO=y
endif
endif
ifeq ($(CONFIG_ZYXEL_SFP_SW_RX_LOS),y)
export ZYXEL_SFP_SW_RX_LOS=y
endif
ifeq ($(CONFIG_ZYXEL_SFP_DETECT_PIN),y)
export ZYXEL_SFP_DETECT_PIN=y
endif
ifeq ($(CONFIG_ZYXEL_SFP_TX_FAULT_PIN),y)
export ZYXEL_SFP_TX_FAULT_PIN=y
endif
ifeq ($(CONFIG_ZYXEL_SFP_TX_DISABLE),y)
export ZYXEL_SFP_TX_DISABLE=y
endif
ifeq ($(CONFIG_ZYXEL_LED_EN_SUPPORT),y)
export ZYXEL_LED_EN_SUPPORT=y
endif 
ifeq ($(CONFIG_ZYXEL_SFP_RX_SLEEP),y)
export ZYXEL_SFP_RX_SLEEP=y
endif
ifeq ($(CONFIG_ZYXEL_ZIGBEE_SUPPORT),y)
export ZYXEL_ZIGBEE_SUPPORT=y
endif
## 2.4G FEM detection
ifeq ($(CONFIG_ZYXEL_FEM_DETECT),y)
export ZYXEL_FEM_DETECT=y
endif
##  Detect board by GPIO
ifeq ($(CONFIG_ZYXEL_BOARD_DETECT_BY_GPIO),y)
export ZYXEL_BOARD_DETECT_BY_GPIO=y
endif
##  USB3.0 or USB2.0 can be set by user manually
ifeq ($(CONFIG_ZYXEL_USB_SET_MANUALLY),y)
export ZYXEL_USB_SET_MANUALLY=y
endif
#############################################

ZYXEL_COMMON_CFLAGS += -DBROADCOM_PLATFORM

ifneq ("$(CONFIG_BRCM_SDK_VERSION)","")
ZYXEL_COMMON_CFLAGS += -DBCM_SDK_$(CONFIG_BRCM_SDK_VERSION)
ZYXEL_COMMON_CFLAGS += -DNEW_MTD_DRIVER
endif

ifeq ($(CONFIG_ZYXEL_VMG8924_B10D_TAAAD_ISOLATE_DMZ),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_VMG8924_B10D_TAAAD_ISOLATE_DMZ
endif

ifeq ($(CONFIG_BRCMSDK416L05_SUPPORT_RTK_SWITCH),y)
ZYXEL_COMMON_CFLAGS += -DSUPPORT_RTK_SWITCH
endif

#WIND Customization for VMG8823-B50B
ifeq ($(CONFIG_ZCFG_VMG8823_B50B_WIND),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_VMG8823_B50B_WIND
endif

ifeq ($(CONFIG_KERNEL_ZYXEL_RS_TRY_5_TIMES),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_RS_TRY_5_TIMES
endif

ifeq ($(CONFIG_ZYXEL_DEDICATED_SFPWAN_INTERFACE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DEDICATED_SFPWAN_INTERFACE
endif

ifeq ($(CONFIG_BRCMSDK$(shell echo $(CONFIG_BRCM_SDK_VERSION))_BRCM_PHY_BONDING),y)
ZYXEL_COMMON_CFLAGS += -DSUPPORT_DSL_BONDING
endif

# LED enum in bcmdrivers/opensource/include/bcm963xx/board.h will use it
ifneq ($(findstring _$(strip $(shell echo $(CONFIG_BRCMSDK$(shell echo $(CONFIG_BRCM_SDK_VERSION))_BRCM_CHIP)))_,_6838_6848_6858_6846_6856_6878_),)
ZYXEL_COMMON_CFLAGS += -DCONFIG_BCM_PON=1
endif

endif
# End of Broadcom platform

########################################################################
# Econet Related
########################################################################
ifeq ("$(strip ${ZCFG_PLATFORM})","ECONET")

export ECONET_SDK_VERSION=$(call qstrip,$(CONFIG_TC_SDK_VERSION))
export ECONET_TARGET_VERSION=$(call qstrip,$(CONFIG_TARGET_BOARD))

ifneq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_ZYXEL_LAN_WAN_WLAN_SHARE_THE_SAME_MAC),)
ZYXEL_COMMON_CFLAGS += -DZYXEL_LAN_WAN_WLAN_SHARE_THE_SAME_MAC
endif

ifeq ($(CONFIG_ZYXEL_VMG8825_T50K_TAAAD_ISOLATE_DMZ),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_VMG8825_T50K_TAAAD_ISOLATE_DMZ
endif

ZYXEL_COMMON_CFLAGS += -DNEW_MTD_DRIVER

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7516)),)
ZYXEL_COMMON_CFLAGS += -DBOOTROM_LARGE_SIZE
endif
ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_BOOTROM_LARGE_SIZE)),)
ZYXEL_COMMON_CFLAGS += -DBOOTROM_LARGE_SIZE
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_MTD_ENCHANCEMENT)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_MTD_ENCHANCEMENT
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_RESERVEAREA_BLOCK)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_RESERVEAREA_BLOCK=$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_RESERVEAREA_BLOCK)
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CT)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CT
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_NAND_BMT)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_NAND_BMT
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_NAND_BADBLOCK_CHECK)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_NAND_BADBLOCK_CHECK
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_PRODUCTIONLINE)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_PRODUCTIONLINE
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7612E)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_WLAN_AC
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7615E)),)
ZYXEL_COMMON_CFLAGS += -DMT7615E
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_WLAN_MT7615_11N)),)
ZYXEL_COMMON_CFLAGS += -DMT7615_11N
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_WLAN_MT7615D)),)
ZYXEL_COMMON_CFLAGS += -DMT7615D -DMT7615_11N -DMT7615E -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_WLAN_MT7915D)),)
ZYXEL_COMMON_CFLAGS += -DMT7915D -DMT7915N -DMT7915E -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC -DTCSUPPORT_WLAN_AX -DTCSUPPORT_WLAN_WPA3
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_WLAN_MT7915A)),)
ZYXEL_COMMON_CFLAGS += -DMT7915A -DMT7915E -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC -DTCSUPPORT_WLAN_AX -DTCSUPPORT_WLAN_WPA3
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7570)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_MT7570
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CT_BOOTLOADER_UPGRADE)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CT_BOOTLOADER_UPGRADE
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_LITTLE_ENDIAN)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_BB_256KB
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7580)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_BB_256KB
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_NAND_FLASH)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_NAND_FLASH
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CT_PON)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CT_PON
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7613E)),)
ZYXEL_COMMON_CFLAGS += -DMT7613E
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7615E)),)
ZYXEL_COMMON_CFLAGS += -DMT7615E
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7610E)),)
ZYXEL_COMMON_CFLAGS += -DMT7610E -DBBUTOWBU -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7612E)),)
ZYXEL_COMMON_CFLAGS += -DMT7612E -DBBUTOWBU -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7512)$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7516)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CPU_EN7512
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7521)$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7527)$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7528)$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7580)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CPU_EN7521
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_RESERVEAREA_EXTEND)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_RESERVEAREA_EXTEND
endif

ifneq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_POWERSAVE_ENABLE),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_POWERSAVE_ENABLE
endif

ifeq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7516),y)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CPU_EN7516
endif

ifeq ($(CONFIG_ZYXEL_ECONET_OPERATION_MODE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ECONET_OPERATION_MODE
endif

ifeq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DMT_MCT),y)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_DMT_MCT
endif

ifeq ($(CONFIG_EN7516SDK_TCSUPPORT_ECNT_MAP),y)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_ECNT_MAP
endif

ifeq ($(CONFIG_TC_SDK_VERSION),"7.3.235.200")
ZYXEL_COMMON_CFLAGS += -DCONFIG_TC_SDK_7_3_235_200
endif
ifeq ($(CONFIG_TC_SDK_VERSION),"7.3.257.150")
ZYXEL_COMMON_CFLAGS += -DCONFIG_TC_SDK_7_3_257_150
endif
ifeq ($(CONFIG_TC_SDK_VERSION),"7.3.245.300")
ZYXEL_COMMON_CFLAGS += -DCONFIG_TC_SDK_7_3_245_300
endif

ifeq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_ZYXEL_DETECT_PRODUCT_TYPE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DETECT_PRODUCT_TYPE
endif

endif
# End of Econet platform

############################################################################################################
# MTK
############################################################################################################
ifeq ("$(strip ${ZCFG_PLATFORM})","MTK")

export MTK_SDK_VERSION=$(call qstrip,$(CONFIG_MTK_SDK_VERSION))
export MTK_TARGET_VERSION=$(call qstrip,$(CONFIG_TARGET_BOARD))

ifneq ($($(shell echo CONFIG_MRD_PRODUCT_NAME)),"")
ZYXEL_COMMON_CFLAGS += -DZYPRJ_$(subst -,_,$(call qstrip,$($(shell echo CONFIG_MRD_PRODUCT_NAME))))
endif

ifneq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_ZYXEL_LAN_WAN_WLAN_SHARE_THE_SAME_MAC),)
ZYXEL_COMMON_CFLAGS += -DZYXEL_LAN_WAN_WLAN_SHARE_THE_SAME_MAC
endif

ifeq ($(CONFIG_ZYXEL_VMG8825_T50K_TAAAD_ISOLATE_DMZ),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_VMG8825_T50K_TAAAD_ISOLATE_DMZ
endif

ZYXEL_COMMON_CFLAGS += -DNEW_MTD_DRIVER

#ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7516)),)
#ZYXEL_COMMON_CFLAGS += -DBOOTROM_LARGE_SIZE
#endif
ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_BOOTROM_LARGE_SIZE)),)
ZYXEL_COMMON_CFLAGS += -DBOOTROM_LARGE_SIZE
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_MTD_ENCHANCEMENT)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_MTD_ENCHANCEMENT
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_RESERVEAREA_BLOCK)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_RESERVEAREA_BLOCK=$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_RESERVEAREA_BLOCK)
endif

#ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CT)),)
#ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CT
#endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_NAND_BMT)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_NAND_BMT
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_NAND_BADBLOCK_CHECK)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_NAND_BADBLOCK_CHECK
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_PRODUCTIONLINE)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_PRODUCTIONLINE
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7612E)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_WLAN_AC
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7615E)),)
ZYXEL_COMMON_CFLAGS += -DMT7615E
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_WLAN_MT7615_11N)),)
ZYXEL_COMMON_CFLAGS += -DMT7615_11N
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_WLAN_MT7615D)),)
ZYXEL_COMMON_CFLAGS += -DMT7615D -DMT7615_11N -DMT7615E -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_WLAN_MT7915D)),)
ZYXEL_COMMON_CFLAGS += -DMT7915D -DMT7915N -DMT7915E -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC -DTCSUPPORT_WLAN_AX -DTCSUPPORT_WLAN_WPA3
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_WLAN_MT7915A)),)
ZYXEL_COMMON_CFLAGS += -DMT7915A -DMT7915E -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC -DTCSUPPORT_WLAN_AX -DTCSUPPORT_WLAN_WPA3
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7570)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_MT7570
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CT_BOOTLOADER_UPGRADE)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CT_BOOTLOADER_UPGRADE
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_LITTLE_ENDIAN)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_BB_256KB
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7580)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_BB_256KB
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_NAND_FLASH)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_NAND_FLASH
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CT_PON)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CT_PON
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7613E)),)
ZYXEL_COMMON_CFLAGS += -DMT7613E
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7615E)),)
ZYXEL_COMMON_CFLAGS += -DMT7615E
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7610E)),)
ZYXEL_COMMON_CFLAGS += -DMT7610E -DBBUTOWBU -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DUAL_WLAN_MT7612E)),)
ZYXEL_COMMON_CFLAGS += -DMT7612E -DBBUTOWBU -DTCSUPPORT_DUAL_WLAN -DTCSUPPORT_WLAN_AC
endif

#ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7512)$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7516)),)
#ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CPU_EN7512
#endif

#ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7521)$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7527)$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7528)$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7580)),)
#ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CPU_EN7521
#endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_RESERVEAREA_EXTEND)),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_RESERVEAREA_EXTEND
endif

ifneq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_POWERSAVE_ENABLE),)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_POWERSAVE_ENABLE
endif

#ifeq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_CPU_EN7516),y)
#ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_CPU_EN7516
#endif

ifeq ($(CONFIG_ZYXEL_MTK_OPERATION_MODE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_MTK_OPERATION_MODE
endif

ifeq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_DMT_MCT),y)
ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_DMT_MCT
endif

#ifeq ($(CONFIG_EN7516SDK_TCSUPPORT_ECNT_MAP),y)
#ZYXEL_COMMON_CFLAGS += -DTCSUPPORT_ECNT_MAP
#endif

ifeq ($(CONFIG_MTK_SDK_VERSION),"7.6.200.N")
ZYXEL_COMMON_CFLAGS += -DCONFIG_MTK_SDK_7_6_200_N
endif

ifeq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_ZYXEL_DETECT_PRODUCT_TYPE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DETECT_PRODUCT_TYPE
endif

endif
# End of Econet platform

########################################################################
# Zyxel Customization
########################################################################
ifeq ($(CONFIG_ABUE_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DABUE_CUSTOMIZATION
endif

ifeq ($(CONFIG_ABOG_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DABOG_CUSTOMIZATION
endif

ifeq ($(CONFIG_ACCL_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DACCL_CUSTOMIZATION
endif

#IAAAA
ifeq ($(CONFIG_IAAAA_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DIAAAA_CUSTOMIZATION
endif

ifeq ($(CONFIG_IAAAA_CUSTOMIZATION_Motorola_VIP1003),y)
ZYXEL_COMMON_CFLAGS += -DIAAAA_CUSTOMIZATION_Motorola_VIP1003
endif

#TAAAF
ifeq ($(CONFIG_TAAAF_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DTAAAF_CUSTOMIZATION
endif

#WIND
ifeq ($(CONFIG_WIND_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DZYPRJ_CUSTOMER_WIND
endif

ifeq ($(CONFIG_WIND_ITALY_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WIND_ITALY_CUSTOMIZATION
ZYXEL_COMMON_CFLAGS += -DWIND_ITALY_CUSTOMIZATION
endif

ifeq ($(CONFIG_ACEN_ENCRYPTED_IMAGE),y)
ZYXEL_COMMON_CFLAGS += -DACEN_ENCRYPTED_IMAGE
endif

ifeq ($(CONFIG_ZYXEL_SFP_LINKUP_DELAYTIMES),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SFP_LINKUP_DELAYTIMES
endif

ifeq ($(CONFIG_ZYXEL_WIND_NEW_XDSL_BEHAVIOR),y)
export ZYXEL_WIND_NEW_XDSL_BEHAVIOR=y
endif

ifeq ($(CONFIG_ZYXEL_SFP_MODULE_SUPPORT),y)
export ZYXEL_SFP_MODULE_SUPPORT=y
endif


#TT
ifeq ($(CONFIG_TAAAB_CUSTOMIZATION_TR069),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_TAAAB_CUSTOMIZATION_TR069
endif

ifeq ($(CONFIG_TAAAB_DSL_BINDING),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_TAAAB_DSL_BINDING
endif

ifeq ($(CONFIG_TAAAB_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_TAAAB_CUSTOMIZATION
endif

ifeq ($(CONFIG_TAAAB_PORTMIRROR),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_TAAAB_PORTMIRROR
endif

ifeq ($(CONFIG_TAAAB_PACKETCAPTURE),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_TAAAB_PACKETCAPTURE
endif

ifeq ($(CONFIG_MSTC_TAAAG_MULTI_USER),y)
ZYXEL_COMMON_CFLAGS += -DMSTC_TAAAG_MULTI_USER
endif

# always set APP_AGENT_SUPPORT ???
ifeq ($(filter y,$(CONFIG_CAAAB_CUSTOMIZATION)),)
ZYXEL_COMMON_CFLAGS += -DAPP_AGENT_SUPPORT
endif

ifeq ($(CONFIG_CAAAB_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DCAAAB_CUSTOMIZATION
endif

#CAAAE
ifeq ($(CONFIG_CAAAE_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DCAAAE_CUSTOMIZATION
endif

#CAAAD
ifeq ($(CONFIG_CAAAD_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DCAAAD_CUSTOMIZATION
endif

#SAAAC
ifeq ($(CONFIG_SAAAC_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DSAAAC_CUSTOMIZATION
endif

#ABUU
ifeq ($(CONFIG_ABUU_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DABUU_CUSTOMIZATION
endif

ifeq ($(CONFIG_ABUU_CUSTOMIZATION_MULTIPLE_CONFIG),y)
ZYXEL_COMMON_CFLAGS += -DABUU_CUSTOMIZATION_MULTIPLE_CONFIG
endif

ifeq ($(CONFIG_ABUU_CUSTOMIZATION_WLAN_SCHEDULER),y)
ZYXEL_COMMON_CFLAGS += -DABUU_CUSTOMIZATION_WLAN_SCHEDULER
endif

ifeq ($(CONFIG_ABUU_CUSTOMIZATION_ONLINE_FW_UPGRADE),y)
ZYXEL_COMMON_CFLAGS += -DABUU_CUSTOMIZATION_ONLINE_FW_UPGRADE
endif

#SAAAD
ifneq ($(strip $(CONFIG_SAAAD_TR98_CUSTOMIZATION)),)
ZYXEL_COMMON_CFLAGS += -DSAAAD_TR98_CUSTOMIZATION
endif

ifeq ($(CONFIG_SAAAD_TR69_WAN_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DSAAAD_TR69_WAN_CUSTOMIZATION
endif

ifeq ($(CONFIG_SAAAD_VLANHUNT_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DSAAAD_VLANHUNT_CUSTOMIZATION
endif

ifeq ($(CONFIG_SAAAD_WAN_AUTO_DETECT_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DSAAAD_WAN_AUTO_DETECT_CUSTOMIZATION
endif

#TAAAD
ifeq ($(CONFIG_TAAAD_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_TAAAD_CUSTOMIZATION
endif

#EAAAA
ifeq ($(CONFIG_EAAAA_CLEAN_ROMD_EVERYTIME_DURING_BOOT_UP),y)
ZYXEL_COMMON_CFLAGS += -DEAAAA_CLEAN_ROMD_EVERYTIME_DURING_BOOT_UP
endif
ifeq ($(CONFIG_EAAAA_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DEAAAA_CUSTOMIZATION
endif
ifeq ($(CONFIG_EAAAA_WAN_AUTO_DETECT),y)
ZYXEL_COMMON_CFLAGS += -DEAAAA_WAN_AUTO_DETECT
endif

#Oi
ifeq ($(CONFIG_OAAAA_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DOAAAA_CUSTOMIZATION
endif
# End of Zyxel Customization

########################################################################
# Zyxel Features
########################################################################
ZYXEL_COMMON_CFLAGS += -D$(ZCFG_PLATFORM)_PLATFORM

ifeq ($(CONFIG_ZYXEL_FEATURE_BITS),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_FEATURE_BITS
endif

ifeq ($(CONFIG_ZYXEL_SFP_MODULE_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SFP_MODULE_SUPPORT
endif

ifeq ($(CONFIG_ZYXEL_SIP_DELAYTIMES),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SIP_DELAYTIMES
endif

ifeq ($(CONFIG_ZYXEL_AP_STEERING),y)
ZYXEL_COMMON_CFLAGS += -DAPSTEERING
endif

ifeq ($(CONFIG_ZyXEL_WEB_REDIRECT),y)
ZYXEL_COMMON_CFLAGS += -DZyXEL_WEB_REDIRECT
endif

ifeq ($(CONFIG_ZyXEL_PCP_WEB_REDIRECT),y)
ZYXEL_COMMON_CFLAGS += -DZyXEL_PCP_WEB_REDIRECT
endif

ifeq ($(CONFIG_ZYXEL_DL_DIAG_CALCULATION),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DL_DIAG_CALCULATION
endif

ifeq ($(CONFIG_DSL_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DSUPPORT_DSL
endif

ifeq ($(CONFIG_ZCFG_LOG_USE_DEBUGCFG),y)
ZYXEL_COMMON_CFLAGS += -DZCFG_LOG_USE_DEBUGCFG
ZYXEL_COMMON_CFLAGS += -DZCFG_ZYUTIL_DEBUG_API
endif

ifeq ($(CONFIG_TARGET_ROOTFS_UBIFS),y)
ZYXEL_COMMON_CFLAGS += -DTARGET_ROOTFS_UBIFS
endif

ifeq ($(CONFIG_ZYXEL_AT_SET_KEY),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_AT_SET_KEY
ifeq ($(CONFIG_ZYXEL_AT_SET_SUPERVISOR_KEY),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_AT_SET_SUPERVISOR_KEY
endif
endif

ifeq ($(CONFIG_ZYXEL_DNS_TRAFFIC_ROUTE_FUZZY_COMPARE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DNS_TRAFFIC_ROUTE_FUZZY_COMPARE
endif

ifeq ($(CONFIG_ZYXEL_OPAL_EXTENDER_WITH_NPACK),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_OPAL_EXTENDER_WITH_NPACK
endif

ifneq ($(strip $(CONFIG_ZYXEL_RMA_FW_SUPPORT)),)
ZYXEL_COMMON_CFLAGS += -DZYXEL_RMA_FW_SUPPORT
endif

ifneq ($(strip $(CONFIG_ZYXEL_IPV6_UPLOAD_DIAG_ENABLE)),)
ZYXEL_COMMON_CFLAGS += -DZYXEL_IPV6_UPLOAD_DIAG_ENABLE
endif

ifeq ($(CONFIG_LTE_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DLTE_SUPPORT
endif

ifeq ($(CONFIG_ZYXEL_NEW_ATSN),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_NEW_ATSN
endif

ifneq ($(strip $(CONFIG_ZYXEL_FIRMWARE_VERSION_EXT)), "")
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_EXT_FW_VER
endif

ifeq ($(CONFIG_ZYXEL_MEMORY_LEAK_DETECT),y)
ZYXEL_COMMON_CFLAGS += -DZCFG_MEMORY_LEAK_DETECT
endif

#define the number of interface for 2.4G and 5G
ifneq ($(strip $(CONFIG_ZYXEL_WIFI_NUM_OF_24G_SSID_INTERFACE)),)
ZYXEL_COMMON_CFLAGS += -DTOTAL_INTERFACE_24G=$(CONFIG_ZYXEL_WIFI_NUM_OF_24G_SSID_INTERFACE)
endif
ifneq ($(strip $(CONFIG_ZYXEL_WIFI_NUM_OF_5G_SSID_INTERFACE)),)
ZYXEL_COMMON_CFLAGS += -DTOTAL_INTERFACE_5G=$(CONFIG_ZYXEL_WIFI_NUM_OF_5G_SSID_INTERFACE)
endif

# F-secure Home Cyber Security
ifeq ($(CONFIG_ZYXEL_HOME_CYBER_SECURITY_FSECURE),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_HOME_CYBER_SECURITY_FSECURE
endif

ifeq ($(CONFIG_KERNEL_ZYXEL_RS_TRY_5_TIMES),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_RS_TRY_5_TIMES
endif

ifeq ($(CONFIG_WIND_Greece_DHCPv6_Client_NTP_Option),y)
ZYXEL_COMMON_CFLAGS += -DWIND_Greece_DHCPv6_Client_NTP_Option
endif

ifeq ($(CONFIG_ZYXEL_USA_PRODUCT),y)
ZYXEL_COMMON_CFLAGS += -DUSA_PRODUCT
endif

ifeq ($(CONFIG_ZYXEL_WLAN_SCHEDULER),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WLAN_SCHEDULER
endif

ifeq ($(CONFIG_ZYXEL_WLAN_SCHEDULER_AUTO_SWITCH_RADIO_ON),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WLAN_SCHEDULER_AUTO_SWITCH_RADIO_ON
endif

ifeq ($(CONFIG_ZYXEL_SP_DOMAIN_TIMER),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SP_DOMAIN_TIMER
endif

ifeq ($(CONFIG_SEND_PADT_BEFORE_DISCOVERY),y)
ZYXEL_COMMON_CFLAGS += -DSEND_PADT_BEFORE_DISCOVERY
endif

ifeq ($(CONFIG_WAN_AUTO_DETECT),y)
ZYXEL_COMMON_CFLAGS += -DWAN_AUTO_DETECT
endif

ifeq ($(CONFIG_ZYXEL_SYS_FWUR_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SYS_FWUR_SUPPORT=y
endif

ifeq ($(CONFIG_BRCMSDK$(shell echo $(CONFIG_BRCM_SDK_VERSION))_ZYXEL_SUPPORT_3G_LED_GREEN_AND_RED),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_3G_LED_GREEN_AND_RED
endif

ifeq ($(CONFIG_INTERNET_LED_DEPEND_ON_DEFAULT_GW),y)
ZYXEL_COMMON_CFLAGS += -DINTERNET_LED_DEPEND_ON_DEFAULT_GW
endif

ifeq ($(CONFIG_BRCMSDK$(shell echo $(CONFIG_BRCM_SDK_VERSION))_ZYXEL_FW_UPGRADE_POWER_LED_BLINK),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_FW_UPGRADE_POWER_LED_BLINK
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_ZYXEL_FW_UPGRADE_POWER_LED_BLINK)),)
ZYXEL_COMMON_CFLAGS += -DZYXEL_FW_UPGRADE_POWER_LED_BLINK
endif

ifeq ($(strip ${CONFIG_ZYXEL_WPS_SPOTLIGHT}),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WPS_SPOTLIGHT
endif

ZYXEL_COMMON_CFLAGS += -DZYXEL_ESMD_UTILIZE_TIMER_THREAD

# Support ONECONNECT
ifeq ($(CONFIG_ZYXEL_ONECONNECT),y)
ZYXEL_COMMON_CFLAGS += -DONECONNECT
endif

ifeq ($(CONFIG_ZYXEL_ONECONNECT_EU),y)
ZYXEL_COMMON_CFLAGS += -DONECONNECT_EU
endif

# Easy Mesh
ifeq ($(CONFIG_ZYXEL_EASYMESH),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_EASYMESH
ZYXEL_COMMON_CFLAGS += -DBUILD_EASYMESH
endif

ifeq ($(CONFIG_ZYXEL_EASYMESH_ROM_CONVERT),y)
ZYXEL_COMMON_CFLAGS += -DEASYMESH_ROM_CONVERT
ZYXEL_COMMON_CFLAGS += -DZYXEL_EASYMESH_ROM_CONVERT
endif

## PCP
ifeq ($(CONFIG_ZYXEL_PCP),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_PCP_SUPPORT
endif

ifeq ($(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_ZYXEL_SUPPORT_LAN_AS_ETHWAN),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_LAN_AS_ETHWAN
ifeq ("$(strip ${ZCFG_PLATFORM})","ECONET")
ZYXEL_COMMON_CFLAGS += -DLAN4_PORTID=$(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_TCSUPPORT_LAN3_PORT)
endif
endif

#Ethernet UNI feature
ifeq ($(CONFIG_ZYXEL_WEB_GUI_ETH_UNI),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WEB_GUI_ETH_UNI
endif

ifeq ($(CONFIG_ZyXEL_PPP_LCP_ECHO),y)
ZYXEL_COMMON_CFLAGS += -DZyXEL_PPP_LCP_ECHO
endif

ifeq ($(CONFIG_ZYXEL_DHCP_OPTION15),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DHCP_OPTION15
endif

ifeq ($(CONFIG_ZyXEL_DHCP_OPTION125),y)
ZYXEL_COMMON_CFLAGS += -DZyXEL_DHCP_OPTION125
endif

ifeq ($(CONFIG_ZYXEL_POWER_MANAGEMENT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_POWER_MGMT
endif

ifeq ($(CONFIG_PROXIMITY_SENSOR_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DSUPPORT_PROXIMITY_SENSOR
endif

ifeq ($(CONFIG_ZYXEL_LED_SWITCH_ACTIVE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_LED_SWITCH_ACTIVE
endif

ifeq ($(CONFIG_ZYXEL_ZYCLI_SUPERVISOR_IPTABLES),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ZYCLI_SUPERVISOR_IPTABLES
endif

ifeq ($(CONFIG_ZYXEL_ZYCLI_SUPERVISOR_TCPDUMP),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ZYCLI_SUPERVISOR_TCPDUMP
endif

#CONFIG_ZYXEL_IPV6_IANA_IAPD
ifeq ($(CONFIG_ZYXEL_IPV6_IANA_IAPD),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_IPV6_IANA_IAPD
endif

ifeq ($(CONFIG_ZYXEL_IPV6_MAP),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_IPV6_MAP
endif

ifeq ($(CONFIG_HAAAA_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DHAAAA_CUSTOMIZATION
endif

#IPv6 Ready Logo Conformance
ifeq ($(CONFIG_ZYXEL_IPV6_READYLOGO_CONFORMANCE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_IPV6_READYLOGO_CONFORMANCE
endif

## TR98 Global Ipv6 Enable
ifeq ($(CONFIG_ZYXEL_IPV6_GLOBAL_ENABLE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_IPV6_GLOBAL_ENABLE_SUPPORT
endif

#DHCPv6s
ifeq ($(CONFIG_ZYXEL_DHCPV6S_LEASE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DHCPV6S_LEASE
endif

#DHCPv6c option
ifeq ($(CONFIG_ZYXEL_DHCPV6C_OPTION),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DHCPV6C_OPTION
endif

#zigbee
ifeq ($(CONFIG_ZYXEL_ZIGBEE_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ZIGBEE_SUPPORT
endif

#Avast agent support
ifeq ($(CONFIG_ZYXEL_AVAST_AGENT_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DAVAST_AGENT_PACKAGE
endif

ifeq ($(CONFIG_KERNEL_ZYXEL_SUPPORT_USB_FALL_BACK_2_0),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_USB_FALL_BACK_2_0
endif

ifeq ($(CONFIG_ZYXEL_WWAN),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WWAN
endif

ifeq ($(CONFIG_ZYXEL_AUTO_REMOVE_INTFGUP_CRIT_OPT60_WIFI_INTF),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_AUTO_REMOVE_INTFGUP_CRIT_OPT60_WIFI_INTF
endif

#CO-FW
ifeq ($(CONFIG_ZYXEL_BOARD_DETECT_BY_GPIO),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_BOARD_DETECT_BY_GPIO
endif

ifeq ($(CONFIG_ZYXEL_SUPPORT_RDPAWAN_CONFIGURE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_RDPAWAN_CONFIGURE
endif

ifeq ($(CONFIG_SAME_FW_FOR_TWO_BOARD),y)
ZYXEL_COMMON_CFLAGS += -DSAME_FW_FOR_TWO_BOARD
endif

ifeq ($(CONFIG_SAME_FW_FOR_PROJECTS),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SAME_FW_FOR_PROJECTS
ZYXEL_COMMON_CFLAGS += -DSAME_FW_FOR_PROJECTS
endif

ifeq ($(CONFIG_ZYXEL_SFP_POWER_MGMT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SFP_POWER_MGMT
endif

#Extender
ifeq ($(CONFIG_ZYXEL_OPAL_EXTENDER),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_OPAL_EXTENDER
endif

ifeq ($(CONFIG_ZYXEL_OPAL_EXTENDER_CE_UNII2C_LED_BEHAVIOR),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_OPAL_EXTENDER_CE_UNII2C_LED_BEHAVIOR
endif

ifeq ($(CONFIG_ZYXEL_DETECT_WAN_IP_CONFLICT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DETECT_WAN_IP_CONFLICT
endif

ifeq ($(CONFIG_ZCFG_MODULE_DEBUG),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZCFG_MODULE_DEBUG
endif

ifeq ($(CONFIG_ZYXEL_WIFI_DELAY_INIT),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_WIFI_DELAY_INIT
endif

ifeq ($(CONFIG_ZYXEL_SUPPORT_SAS_CBSD),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_SAS_CBSD
endif

ifeq ($(CONFIG_ALTIBOX_CUSTOMIZATION),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ALTIBOX_CUSTOMIZATION
endif

#QoS fq-codel
ifeq ($(CONFIG_ZYXEL_FQ_CODEL),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_FQ_CODEL
endif

#CELLWAN support
ifeq ($(CONFIG_ZYXEL_CELLWAN_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_CELLWAN_SUPPORT
endif

ifeq ($(CONFIG_ZYXEL_SEND_NEW_CONNECTION_NOTIFICATION),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SEND_NEW_CONNECTION_NOTIFICATION
endif

ifeq ($(CONFIG_ZYXEL_WLAN_BLOCK_OPEN),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WLAN_BLOCK_OPEN
endif

ifeq ($(CONFIG_ZCFG_CONFIG_ENCRYPT),y)
ZYXEL_COMMON_CFLAGS += -DZCFG_CONFIG_ENCRYPT
endif

ifeq ($(CONFIG_ZYXEL_FW_SIGNATURE_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DFW_SIGNATURE_SUPPORT
endif

ifeq ($(CONFIG_ZYXEL_INDEPENDENT_WPS_METHODS),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_INDEPENDENT_WPS_METHODS
endif

ifeq ($(CONFIG_ZYXEL_FWUPGRADE_DHCP_SUB_OPTION43),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_FWUPGRADE_DHCP_SUB_OPTION43
endif

ifeq ($(CONFIG_ZYXEL_SONIQ),y)
ZYXEL_COMMON_CFLAGS += -DBUILD_SONIQ
endif

ifeq ($(CONFIG_ZYXEL_SONIQ_ROM_CONVERT),y)
ZYXEL_COMMON_CFLAGS += -DSONIQ_ROM_CONVERT
endif

#ONESSID
ifeq ($(CONFIG_ZYXEL_ONESSID),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ONESSID
endif

ifeq ($(CONFIG_ZYXEL_ELIMINATE_DHCP_LEASE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ELIMINATE_DHCP_LEASE
endif

ifneq ($(strip $(CONFIG_ZYXEL_WIFI_NUM_OF_5G_SSID_INTERFACE)),)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_WIFI_NUM_OF_5G_SSID_INTERFACE=$(CONFIG_ZYXEL_WIFI_NUM_OF_5G_SSID_INTERFACE)
endif

ifneq ($(strip $(CONFIG_ZYXEL_WIFI_NUM_OF_24G_SSID_INTERFACE)),)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_WIFI_NUM_OF_24G_SSID_INTERFACE=$(CONFIG_ZYXEL_WIFI_NUM_OF_24G_SSID_INTERFACE)
endif

ifeq ($(CONFIG_TARGET_ROOTFS_JFFS2),y)
ZYXEL_COMMON_CFLAGS += -DTARGET_ROOTFS_JFFS2
endif

ifeq ($(CONFIG_BIG_ENDIAN),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_B_ENDIAN
else
ZYXEL_COMMON_CFLAGS += -DZYXEL_L_ENDIAN
endif

ifeq ($(CONFIG_MSTC_RAAAA_MULTI_USER),y)
ZYXEL_COMMON_CFLAGS += -DMSTC_RAAAA_MULTI_USER
endif

ifeq ($(CONFIG_TENDER_TAAAB_FEATURE),y)
ZYXEL_COMMON_CFLAGS += -DTENDER_TAAAB_FEATURE
endif

ifeq ($(CONFIG_ZYXEL_TAAAG_TR69ALG),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_TAAAG_TR69ALG
endif

ifeq ($(CONFIG_ZYXEL_WLAN_WORK_24_HOURS),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WLAN_WORK_24_HOURS
endif

ifeq ($(CONFIG_ZYXEL_TR140),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_TR140
endif

ifeq ($(CONFIG_ZYXEL_IGMPDIAG),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_IGMPDIAG
endif

ifeq ($(CONFIG_ZYXEL_TAAAB_PARTIAL_RESTORE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_TAAAB_PARTIAL_RESTORE
endif

# Fixed WAN MAC address sequence arrangement
ifeq ($(CONFIG_ZYXEL_FIX_WAN_MAC),y)
ZYXEL_COMMON_CFLAGS += -DFIX_WAN_MAC
endif

# All WAN used the same MAC, only supported on MTK platform
ifeq ($(CONFIG_ZYXEL_ONE_MAC_ADDRESS),y)
ZYXEL_COMMON_CFLAGS += -DONE_MAC_ADDRESS
endif

ifeq ($(CONFIG_ZYXEL_ENCRYPTKEY_USE_AT_KEY),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ENCRYPTKEY_USE_AT_KEY
endif

ifeq ($(CONFIG_ZYXEL_GRE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_GRE_SUPPORT -DZYXEL_X_GRE
endif

ifeq ($(CONFIG_ZYXEL_ECONET_CALA_DATA_RE_WRITE_TO_FLASH),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ECONET_CALA_DATA_RE_WRITE_TO_FLASH
endif

ifeq ($(CONFIG_ZYXEL_MULTI_ROM_FILE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_MULTI_ROM_FILE
endif

ifeq ($(CONFIG_ZYXEL_IPTV_SSID_PRIORITY_WPS_PBC),y)
ZYXEL_COMMON_CFLAGS += -DGUEST_SSID_WPS_PBC
ZYXEL_COMMON_CFLAGS += -DWPS_IPTV_GUEST_NUM=$(CONFIG_ZYXEL_WPS_IPTV_GUEST_WIFI_NUM)
endif

#lifemote
ifeq ($(CONFIG_ZYXEL_SUPPORT_LIFEMOTE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_LIFEMOTE
endif

ifeq ($(CONFIG_X_ZYXEL_SUPPORT_LIFEMOTE),y)
ZYXEL_COMMON_CFLAGS += -DX_ZYXEL_SUPPORT_LIFEMOTE
endif

ifeq ($(CONFIG_ABWW_ALLOW_UPGRADE_FW_ID_WITH_DUMMY),y)
ZYXEL_COMMON_CFLAGS += -DABWW_ALLOW_UPGRADE_FW_ID_WITH_DUMMY
endif

ifeq ($(CONFIG_OPENSSL_VERSION_1_0_2n),y)
ZYXEL_COMMON_CFLAGS += -DOPENSSL_VERSION_1_0_2n
endif

ifneq ($(strip $(CONFIG_ZYXEL_FLASH_ID_CHECK_PREVENT_DOWNGRADE)), "")
ZYXEL_COMMON_CFLAGS += -DFLASH_ID_CHECK_PREVENT_DOWNGRADE="'\"$(CONFIG_ZYXEL_FLASH_ID_CHECK_PREVENT_DOWNGRADE)\"'"
endif

ifeq ($(CONFIG_ZYXEL_REMOTE_ACCESS_PRIVILEGE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_REMOTE_ACCESS_PRIVILEGE
ifeq ($(CONFIG_ZYXEL_REMOTE_ACCESS_PRIVILEGE_ROM_CONVERT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_REMOTE_ACCESS_PRIVILEGE_ROM_CONVERT
endif
endif

ifeq ($(strip $(CONFIG_ZYXEL_LANDING_PAGE_FEATURE)),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_LANDING_PAGE_FEATURE
endif

ifneq ($(strip $(CONFIG_$(shell echo $(CONFIG_CUSTOM_SDK_PREFIX))_ZYXEL_SUPPORT_DEFCFG)),)
ZYXEL_COMMON_CFLAGS+=-DZYXEL_SUPPORT_DEFCFG
endif

#ifeq ($(CONFIG_ZCFG_QUERY_TR98_PARM_ATTR_LIST),y)
ZYXEL_COMMON_CFLAGS += -DZCFG_UTILIZE_TR98_OBJ_ALIAS_ON_TR181
#endif

ifeq ($(CONFIG_ZCFG_QUERY_TR98_PARM_ATTR_LIST),y)
ZYXEL_COMMON_CFLAGS += -DZCFG_QUERY_TR98_PARM_ATTR_LIST
endif

ifeq ($(CONFIG_ZCFG_TR098181_OBJECT_MAPPING_NUM_NAME_CONVERT),y)
ZYXEL_COMMON_CFLAGS += -DTR098181_OBJECT_MAPPING_NUM_NAME_CONVERT
endif

ifeq ($(CONFIG_CORE_DUMP_ZCMD),y)
ZYXEL_COMMON_CFLAGS += -DCORE_DUMP_ZCMD
endif

ifeq ($(CONFIG_ZYXEL_FW_ID_CHECK_FW_UPGRADE),y)
ZYXEL_COMMON_CFLAGS += -DFW_ID_CHECK_FW_UPGRADE
endif

ifeq ($(CONFIG_ZYXEL_NO_UPGRADE_SAME_FW),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_NO_UPGRADE_SAME_FW
endif

ifeq ($(CONFIG_ZYXEL_FW_ID_CHECK_PREVENT_DOWNGRADE),y)
ZYXEL_COMMON_CFLAGS += -DFW_ID_CHECK_PREVENT_DOWNGRADE
endif

ifeq ($(CONFIG_ZYXEL_MODEL_ID_CHECK_FW_UPGRADE),y)
ZYXEL_COMMON_CFLAGS += -DMODEL_ID_CHECK_FW_UPGRADE
endif

ifeq ($(CONFIG_ZyXEL_Online_Firmware_Upgrade),y)
ZYXEL_COMMON_CFLAGS += -DZyXEL_Online_Firmware_Upgrade
endif

ifeq ($(CONFIG_XPON_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_XPON_SUPPORT
endif

ifeq ($(CONFIG_ZYXEL_RESET_WATCHDOG),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_RESET_WATCHDOG
endif

ifneq ($(strip $(CONFIG_BUILD_ZYXEL_PHONE_DECT_SUPPORT)),)
ZYXEL_COMMON_CFLAGS += -DZYXEL_PHONE_DECT_SUPPORT=1
endif

ifeq ($(CONFIG_ZyXEL_IPP_PRINTSERVER),y)
ZYXEL_COMMON_CFLAGS += -DZyXEL_IPP_PRINTSERVER
endif

ifeq ($(CONFIG_ZYXEL_SAVE_LOG_TO_FLASH),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SAVE_LOG_TO_FLASH
endif

ifneq ($(strip $(CONFIG_SAAAD_RELEASE_DHCP_PPP_BEFORE_IFDOWN)),)
ZYXEL_COMMON_CFLAGS += -DSAAAD_RELEASE_DHCP_PPP_BEFORE_IFDOWN
endif

ifeq ($(CONFIG_SAAAD_RANDOM_PASSWORD),y)
ZYXEL_COMMON_CFLAGS += -DSAAAD_RANDOM_PASSWORD
endif

ifeq ($(CONFIG_ZCFG_VMG8825_B50B_WIND),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ZCFG_VMG8825_B50B_WIND
endif

ifeq ($(CONFIG_ZCFG_VMG8825_B50B_Generic),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ZCFG_VMG8825_B50B_Generic
endif

ifeq ($(CONFIG_ZCFG_VMG8825_B50B_Altibox),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ZCFG_VMG8825_B50B_Altibox
endif

#SHA512 Password
ifeq ($(CONFIG_ZYXEL_HASH_ACCOUNT_PASSWORD_BY_SHA512), y)
ZYXEL_COMMON_CFLAGS += -DSHA512_PASSWD
ifneq ($(CONFIG_ZYXEL_HASH_ACCOUNT_PASSWORD_BY_SHA512_START_VER),)
ZYXEL_COMMON_CFLAGS += -DZYXEL_HASH_ACCOUNT_PASSWORD_BY_SHA512_START_VER=$(CONFIG_ZYXEL_HASH_ACCOUNT_PASSWORD_BY_SHA512_START_VER)
endif
endif

#SAAAE
ifeq ($(CONFIG_SOL_TR69_3G_Backup),y)
ZYXEL_COMMON_CFLAGS += -DSOL_TR69_3G_Backup
endif
ifeq ($(CONFIG_SOL_TR69_TRUSTDOMAIN),y)
ZYXEL_COMMON_CFLAGS += -DSOL_TR69_TRUSTDOMAIN
endif
ifeq ($(CONFIG_SOL_TR69_LOGINACCOUNT),y)
ZYXEL_COMMON_CFLAGS += -DSOL_TR69_LOGINACCOUNT
endif

ifeq ($(CONFIG_ZYXEL_SUPPORT_TR98_LOGIN_ACCOUNT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_TR98_LOGIN_ACCOUNT
endif

ifeq ($(CONFIG_ZYXEL_WEB_WIRELESS_NEW_VERSION_ONE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WEB_WIRELESS_NEW_VERSION_ONE
endif

#Support WiFi Security Mode WEP/WPA/WPA-MIXED/WPA2-PSK
ifeq ($(CONFIG_ZYXEL_WIFI_SUPPORT_WEP_WPA_MIXMODE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_WIFI_SUPPORT_WEP_WPA_MIXMODE
endif

ifeq ($(CONFIG_ZYXEL_CONFIG_IGNORE_OWNER_CHECK),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_CONFIG_IGNORE_OWNER_CHECK
endif

## Misc partition
ifeq ($(CONFIG_ZYXEL_SUPPORT_MISC),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_MISC
ifneq ($(strip ${CONFIG_ZYXEL_CUSTOMISED_MISC_NAME}),)
ZYXEL_COMMON_CFLAGS += -DZYXEL_CUSTOMISED_MISC_NAME="'\"$(CONFIG_ZYXEL_CUSTOMISED_MISC_NAME)\"'"
endif
endif

#PPTP Support
ifeq ($(CONFIG_KERNEL_ZYXEL_PPTP_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_PPTP_SUPPORT
endif

ifeq ($(CONFIG_ZYXEL_G729_AND_LOGIN_PRIVILEGE_CONVERT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_G729_AND_LOGIN_PRIVILEGE_CONVERT
endif

ifeq ($(CONFIG_ZYXEL_DISABLE_PMF_ROM_CONVERT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_DISABLE_PMF_ROM_CONVERT
endif

#VOICE
ifeq ($(CONFIG_BUILD_ZYXEL_VOICE_CODEC_G729_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_VOICE_CODEC_G729_SUPPORT=1
endif

ifeq ($(CONFIG_ZYXEL_HIDE_USB_PAGE_IN_GUI),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_HIDE_USB_PAGE_IN_GUI
endif

ifeq ($(CONFIG_ZYXEL_ROMCONVERT_GUI_VOIP_SHOW_IOP_FLAGS_IGNORE_CHECK_CONTACT_URL_IN_REGISTER_200OK),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ROMCONVERT_GUI_VOIP_SHOW_IOP_FLAGS_IGNORE_CHECK_CONTACT_URL_IN_REGISTER_200OK
endif

# tr69 data usage
ifeq ($(CONFIG_ZYXEL_TR69_DATA_USAGE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_TR69_DATA_USAGE
endif

ifeq ($(CONFIG_ZYXEL_TR69_RELAUNCH),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_TR69_RELAUNCH
endif

ifeq ($(CONFIG_ZYXEL_CHANNEL_SKIP_LIST_ROM_CONVERT),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_CHANNEL_SKIP_LIST_ROM_CONVERT
endif

# Fsecure related compiler flag
ifeq ($(CONFIG_ZYXEL_SKIP_IPV6_DNS_ROMCONV_FSECURE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SKIP_IPV6_DNS_ROMCONV_FSECURE
endif

ifneq ($($(shell echo CONFIG_BRCMSDK$(CONFIG_BRCM_SDK_VERSION)_ZYXEL_PRODUCT)),"")
ZYXEL_COMMON_CFLAGS += -DZYPRJ_$($(shell echo CONFIG_BRCMSDK$(CONFIG_BRCM_SDK_VERSION)_ZYXEL_PRODUCT))=1
endif

# support RDPA
ifeq ($($(shell echo CONFIG_BRCMSDK$(CONFIG_BRCM_SDK_VERSION)_BUILD_RDPA)),y)
ZYXEL_COMMON_CFLAGS += -DSUPPORT_RDPA -DCHIP_$(BRCM_CHIP)
endif

ifeq ($(CONFIG_ZYXEL_CUSTOMIZATION_DEVICELOG),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_CUSTOMIZATION_DEVICELOG
endif

ifeq ($(CONFIG_ZYXEL_CUSTOMIZATION_SYSLOG),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_CUSTOMIZATION_SYSLOG
endif

ifeq ($(ZYXEL),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL=1
endif

ifeq ($(strip ${ZYXEL_RSA_FORMAT}),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_RSA_FORMAT=1
endif

ifeq ($(CONFIG_ZYXEL_MODSW_ZYEE),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_MODSW_ZYEE
endif

# It is not proper to use package name as the condition
# Should modify in future

#zyinetled
ifeq ($(CONFIG_PACKAGE_kmod-zyinetled),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ZYINETLED
endif

# zupnp
ifeq ($(CONFIG_PACKAGE_zupnp),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_PACKAGE_zupnp
endif

# miniupnpd
ifeq ($(CONFIG_PACKAGE_miniupnpd),y)
ZYXEL_COMMON_CFLAGS += -DMINIUPNPD
endif

# RESTful API Server
ifeq ($(CONFIG_PACKAGE_zhttpd_rest),y)
ZYXEL_COMMON_CFLAGS += -DPACKAGE_zhttpd_rest
endif

ifeq ($(CONFIG_PACKAGE_kmod-usb-core),y)
ZYXEL_COMMON_CFLAGS += -DBUILD_PACKAGE_USB
endif

ifeq ($(CONFIG_PACKAGE_zhotplugd),y)
ZYXEL_COMMON_CFLAGS += -DBUILD_PACKAGE_zhotplugd
endif

ifeq ($(CONFIG_PACKAGE_ZyIMS),y)
ZYXEL_COMMON_CFLAGS += -DBUILD_PACKAGE_ZyIMS
ZYXEL_COMMON_CFLAGS += -DCONFIG_PACKAGE_ZyIMS
ZYXEL_COMMON_CFLAGS += -DZYIMS_SUPPORT=1
endif
ifeq ($(CONFIG_ZYXEL_CELLWAN_SUPPORT),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_CELLWAN_SUPPORT
endif

ifneq ($(strip $(CONFIG_PACKAGE_zycfgfilter)),)
ZYXEL_COMMON_CFLAGS += -DZYCFGFILTER_SUPPORT
endif

ifeq ($(strip $(CONFIG_PACKAGE_tmsctl)),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_ETHOAM_TMSCTL
endif

ifeq ($(CONFIG_PACKAGE_ztr64),y)
ZYXEL_COMMON_CFLAGS += -DZCFG_TR64
endif

ifeq ($(CONFIG_ZYXEL_IGNORE_PASSWORD_CHK_IN_SECURITY_FILTER_TBL),y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_IGNORE_PASSWORD_CHK_IN_SECURITY_FILTER_TBL
endif

ifeq ($(CONFIG_ZYXEL_MULTI_WAN),y)
ZYXEL_COMMON_CFLAGS += -DCONFIG_ZYXEL_MULTI_WAN
endif

ifeq ($(CONFIG_ZYXEL_SUPPORT_ATCK_ENCRYPTION), y)
ZYXEL_COMMON_CFLAGS += -DZYXEL_SUPPORT_ATCK_ENCRYPTION
endif

# End of Zyxel Features
########################################################################
###    END: Zyxel common compile flags
########################################################################
ZYXEL_APP_CFLAGS += $(ZYXEL_COMMON_CFLAGS)
ZYXEL_APP_LDFLAGS += $(ZYXEL_COMMON_LDFLAGS)
ZYXEL_LIB_CFLAGS += $(ZYXEL_COMMON_CFLAGS)
ZYXEL_LIB_LDFLAGS += $(ZYXEL_COMMON_LDFLAGS)

endif #__zyxel_rules_inc
