#ifndef _ZCFG_RDM_OID_H
#define _ZCFG_RDM_OID_H

#define RDM_OID_DEVICE                           0 	/*Device*/
#define RDM_OID_SERVICE                          176	/*Device.Services*/
#define RDM_OID_VOICE_SRV                        232	/*Device.Services.VoiceService.i*/
#define RDM_OID_VOICE_CAPB                       368	/*Device.Services.VoiceService.i.Capabilities*/
#define RDM_OID_VOICE_CAPB_SIP                   1704	/*Device.Services.VoiceService.i.Capabilities.SIP*/
#define RDM_OID_VOICE_CAPB_MGCP                  2200	/*Device.Services.VoiceService.i.Capabilities.MGCP*/
#define RDM_OID_VOICE_CAPB_H323                  2296	/*Device.Services.VoiceService.i.Capabilities.H323*/
#define RDM_OID_VOICE_CAPB_CODEC                 2432	/*Device.Services.VoiceService.i.Capabilities.Codec.i*/
#define RDM_OID_VOICE_PROF                       2728	/*Device.Services.VoiceService.i.VoiceProfile.i*/
#define RDM_OID_VOICE_PROF_SRV_PRO_INFO          4704	/*Device.Services.VoiceService.i.VoiceProfile.i.ServiceProviderInfo*/
#define RDM_OID_VOICE_PROF_SIP                   4920	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP*/
#define RDM_OID_VOICE_PROF_SIP_SUBSCRIBE_OBJ     7896	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_PROF_SIP_RESP_MAP_OBJ      8152	/*Device.Services.VoiceService.i.VoiceProfile.i.SIP.ResponseMap.i*/
#define RDM_OID_VOICE_PROF_RTP                   8328	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP*/
#define RDM_OID_VOICE_PROF_RTP_RTCP              8624	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.RTCP*/
#define RDM_OID_VOICE_PROF_RTP_SRTP              8800	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.SRTP*/
#define RDM_OID_VOICE_PROF_RTP_REDUNDANCY        9016	/*Device.Services.VoiceService.i.VoiceProfile.i.RTP.Redundancy*/
#define RDM_OID_VOICE_PROF_NUM_PLAN              9392	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan*/
#define RDM_OID_VOICE_PROF_NUM_PLAN_PREFIX_INFO  9808	/*Device.Services.VoiceService.i.VoiceProfile.i.NumberingPlan.PrefixInfo.i*/
#define RDM_OID_VOICE_PROF_TONE                  10184	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone*/
#define RDM_OID_VOICE_PROF_TONE_EVENT            10360	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Event.i*/
#define RDM_OID_VOICE_PROF_TONE_DESCRIPTION      10496	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Description.i*/
#define RDM_OID_VOICE_PROF_TONE_PATTERN          10832	/*Device.Services.VoiceService.i.VoiceProfile.i.Tone.Pattern.i*/
#define RDM_OID_VOICE_PROF_FAX_T38               11448	/*Device.Services.VoiceService.i.VoiceProfile.i.FaxT38*/
#define RDM_OID_VOICE_LINE                       11744	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i*/
#define RDM_OID_VOICE_LINE_SIP                   12360	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP*/
#define RDM_OID_VOICE_LINE_SIP_EVENT_SUBS        12816	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.SIP.EventSubscribe.i*/
#define RDM_OID_VOICE_LINE_RINGER                12992	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer*/
#define RDM_OID_VOICE_LINE_RINGER_EVENT          13168	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Event.i*/
#define RDM_OID_VOICE_LINE_RINGER_DESCRIPTION    13304	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Description.i*/
#define RDM_OID_VOICE_LINE_RINGER_PATTERN        13560	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Ringer.Pattern.i*/
#define RDM_OID_VOICE_LINE_CALLING_FEATURE       13776	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.CallingFeatures*/
#define RDM_OID_VOICE_LINE_PROCESSING            16272	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.VoiceProcessing*/
#define RDM_OID_VOICE_LINE_CODEC                 16768	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec*/
#define RDM_OID_VOICE_LINE_CODEC_LIST            17104	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Codec.List.i*/
#define RDM_OID_VOICE_LINE_SESSION               17560	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Session.i*/
#define RDM_OID_VOICE_LINE_STATS                 17816	/*Device.Services.VoiceService.i.VoiceProfile.i.Line.i.Stats*/
#define RDM_OID_VOICE_PHY_INTF                   19112	/*Device.Services.VoiceService.i.PhyInterface.i*/
#define RDM_OID_VOICE_FXS_CID                    20208	/*Device.Services.VoiceService.i.PhyInterface.i.X_ZYXEL_CID*/
#define RDM_OID_VOICE_PSTN                       20344	/*Device.Services.VoiceService.i.X_ZYXEL_PSTN.i*/
#define RDM_OID_VOICE_COMMON                     20640	/*Device.Services.VoiceService.i.X_ZYXEL_Common*/
#define RDM_OID_VOICE_PHONE_BOOK                 21616	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook*/
#define RDM_OID_SPEED_DIAL_BOOK                  21672	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook*/
#define RDM_OID_SPEED_DIAL_BOOK_LIST             21768	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.SpeedDialBook.List.i*/
#define RDM_OID_CALL_POLICY_BOOK                 22064	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook*/
#define RDM_OID_CALL_POLICY_BOOK_LIST            22400	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.CallPolicyBook.List.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK 22696	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_IF_LIST 22792	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i*/
#define RDM_OID_VOICE_INTERNAL_PHONE_NUMBER_BOOK_PORT_LIST 22928	/*Device.Services.VoiceService.i.X_ZYXEL_VoicePhoneBook.InternalPhoneNumberBook.InterfaceList.i.PortList.i*/
#define RDM_OID_VOICE_FXO                        23024	/*Device.Services.VoiceService.i.X_ZYXEL_FXO*/
#define RDM_OID_VOICE_FXO_PORT                   23120	/*Device.Services.VoiceService.i.X_ZYXEL_FXO.Port.i*/
#define RDM_OID_VOICE_CALL_STATUS                23576	/*Device.Services.VoiceService.i.X_ZYXEL_CALL_STATUS*/
#define RDM_OID_MGMT_SRV                         23952	/*Device.ManagementServer*/
#define RDM_OID_MGMT_SRV_MGAB_DEV                27568	/*Device.ManagementServer.ManageableDevice.i*/
#define RDM_OID_MGMT_SRV_AUTO_TRANS_COMPLETE_POL 27904	/*Device.ManagementServer.AutonomousTransferCompletePolicy*/
#define RDM_OID_MGMT_SRV_DL_AVAIL                28120	/*Device.ManagementServer.DownloadAvailability*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT        28176	/*Device.ManagementServer.DownloadAvailability.Announcement*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_ANNCMNT_GROUP  28352	/*Device.ManagementServer.DownloadAvailability.Announcement.Group.i*/
#define RDM_OID_MGMT_SRV_DL_AVAIL_QUERY          28568	/*Device.ManagementServer.DownloadAvailability.Query*/
#define RDM_OID_MGMT_SRV_DU_STATE_CHANGE_COMPL_POL 28744	/*Device.ManagementServer.DUStateChangeComplPolicy*/
#define RDM_OID_MGMT_SRV_EMBEDED_DEV             28960	/*Device.ManagementServer.EmbeddedDevice.i*/
#define RDM_OID_MGMT_SRV_VIRTUAL_DEV             29376	/*Device.ManagementServer.VirtualDevice.i*/
#define RDM_OID_MGMT_SRV_INFORM_PAR              29632	/*Device.ManagementServer.InformParameter.i*/
#define RDM_OID_TIME                             29848	/*Device.Time*/
#define RDM_OID_USR_INTF                         30944	/*Device.UserInterface*/
#define RDM_OID_USR_INTF_REMO_ACESS              31960	/*Device.UserInterface.RemoteAccess*/
#define RDM_OID_USR_INTF_LOCAL_DISP              32176	/*Device.UserInterface.LocalDisplay*/
#define RDM_OID_IFACE_STACK                      32552	/*Device.InterfaceStack.i*/
#define RDM_OID_ETH                              32808	/*Device.Ethernet*/
#define RDM_OID_ETH_RMON_ST                      33024	/*Device.Ethernet.RMONStats.i*/
#define RDM_OID_ETH_IFACE                        33960	/*Device.Ethernet.Interface.i*/
#define RDM_OID_ETH_INTF_ST                      34936	/*Device.Ethernet.Interface.i.Stats*/
#define RDM_OID_ETH_LINK                         35592	/*Device.Ethernet.Link.i*/
#define RDM_OID_ETH_LINK_ST                      36208	/*Device.Ethernet.Link.i.Stats*/
#define RDM_OID_ETH_VLAN_TERM                    36864	/*Device.Ethernet.VLANTermination.i*/
#define RDM_OID_ETH_VLAN_TERM_ST                 37440	/*Device.Ethernet.VLANTermination.i.Stats*/
#define RDM_OID_BRIDGING                         38096	/*Device.Bridging*/
#define RDM_OID_BRIDGING_BR                      38552	/*Device.Bridging.Bridge.i*/
#define RDM_OID_BRIDGING_BR_PORT                 39088	/*Device.Bridging.Bridge.i.Port.i*/
#define RDM_OID_BRIDGING_BR_PORT_ST              39944	/*Device.Bridging.Bridge.i.Port.i.Stats*/
#define RDM_OID_BRIDGING_BR_VLAN                 40600	/*Device.Bridging.Bridge.i.VLAN.i*/
#define RDM_OID_BRIDGING_BR_VLANPORT             40816	/*Device.Bridging.Bridge.i.VLANPort.i*/
#define RDM_OID_BRIDGING_FILTER                  41072	/*Device.Bridging.Filter.i*/
#define RDM_OID_PPP                              42488	/*Device.PPP*/
#define RDM_OID_PPP_IFACE                        42624	/*Device.PPP.Interface.i*/
#define RDM_OID_PPP_IFACE_PPPOA                  44400	/*Device.PPP.Interface.i.PPPoA*/
#define RDM_OID_PPP_IFACE_PPPOE                  44456	/*Device.PPP.Interface.i.PPPoE*/
#define RDM_OID_PPP_IFACE_IPCP                   44672	/*Device.PPP.Interface.i.IPCP*/
#define RDM_OID_PPP_INTF_IPV6CP                  44928	/*Device.PPP.Interface.i.IPV6CP*/
#define RDM_OID_PPP_IFACE_STAT                   45064	/*Device.PPP.Interface.i.Stats*/
#define RDM_OID_IP                               45720	/*Device.IP*/
#define RDM_OID_IP_IFACE                         46136	/*Device.IP.Interface.i*/
#define RDM_OID_IP_IFACE_V4_ADDR                 49032	/*Device.IP.Interface.i.IPv4Address.i*/
#define RDM_OID_IP_IFACE_V6_ADDR                 49448	/*Device.IP.Interface.i.IPv6Address.i*/
#define RDM_OID_IP_IFACE_V6_PREFIX               50064	/*Device.IP.Interface.i.IPv6Prefix.i*/
#define RDM_OID_IP_IFACE_STAT                    50800	/*Device.IP.Interface.i.Stats*/
#define RDM_OID_IP_ACTIVE_PORT                   51456	/*Device.IP.ActivePort.i*/
#define RDM_OID_IP_DIAG                          51712	/*Device.IP.Diagnostics*/
#define RDM_OID_IP_DIAG_IPPING                   52088	/*Device.IP.Diagnostics.IPPing*/
#define RDM_OID_IP_DIAG_TRACE_RT                 52824	/*Device.IP.Diagnostics.TraceRoute*/
#define RDM_OID_IP_DIAG_TRACERT_RT_HOPS          53360	/*Device.IP.Diagnostics.TraceRoute.RouteHops.i*/
#define RDM_OID_IP_DIAG_DL_DIAG                  53576	/*Device.IP.Diagnostics.DownloadDiagnostics*/
#define RDM_OID_IP_DIAG_DL_DIAG_PER_CONN_RST     55472	/*Device.IP.Diagnostics.DownloadDiagnostics.PerConnectionResult.i*/
#define RDM_OID_IP_DIAG_DL_DIAG_INCREM_RST       55848	/*Device.IP.Diagnostics.DownloadDiagnostics.IncrementalResult.i*/
#define RDM_OID_IP_DIAG_UL_DIAG                  56104	/*Device.IP.Diagnostics.UploadDiagnostics*/
#define RDM_OID_IP_DIAG_UL_DIAG_PER_CONN_RST     58040	/*Device.IP.Diagnostics.UploadDiagnostics.PerConnectionResult.i*/
#define RDM_OID_IP_DIAG_UL_DIAG_INCREM_RST       58416	/*Device.IP.Diagnostics.UploadDiagnostics.IncrementalResult.i*/
#define RDM_OID_IP_DIAG_UDP_ECHO_CFG             58672	/*Device.IP.Diagnostics.UDPEchoConfig*/
#define RDM_OID_IP_DIAG_UDP_ECHO_DIAG            59208	/*Device.IP.Diagnostics.UDPEchoDiagnostics*/
#define RDM_OID_IP_DIAG_UDP_ECHO_PAK_RST         60064	/*Device.IP.Diagnostics.UDPEchoDiagnostics.IndividualPacketResult.i*/
#define RDM_OID_IP_DIAG_SVR_SELECT_DIAG          60440	/*Device.IP.Diagnostics.ServerSelectionDiagnostics*/
#define RDM_OID_IP_DIAG_CAPABILITIES             60976	/*Device.IP.Diagnostics.Capabilities*/
#define RDM_OID_IP_DIAG_CAP_PERF_DIAG            61032	/*Device.IP.Diagnostics.Capabilities.PerformanceDiagnostic*/
#define RDM_OID_MAP                              61368	/*Device.MAP*/
#define RDM_OID_MAP_DOMAIN                       61504	/*Device.MAP.Domain.i*/
#define RDM_OID_MAP_DOMAIN_RULE                  62120	/*Device.MAP.Domain.i.Rule.i*/
#define RDM_OID_MAP_DOMAIN_IFACE                 62616	/*Device.MAP.Domain.i.Interface*/
#define RDM_OID_MAP_DOMAIN_IFACE_STAT            62912	/*Device.MAP.Domain.i.Interface.Stats*/
#define RDM_OID_CAPT_PORTAL                      63568	/*Device.CaptivePortal*/
#define RDM_OID_ROUTING                          63784	/*Device.Routing*/
#define RDM_OID_ROUTING_ROUTER                   63880	/*Device.Routing.Router.i*/
#define RDM_OID_ROUTING_ROUTER_V4_FWD            64256	/*Device.Routing.Router.i.IPv4Forwarding.i*/
#define RDM_OID_ROUTING_ROUTER_V6_FWD            65112	/*Device.Routing.Router.i.IPv6Forwarding.i*/
#define RDM_OID_ROUTING_RIP                      65568	/*Device.Routing.RIP*/
#define RDM_OID_ROUTING_RIP_INTF_SET             65744	/*Device.Routing.RIP.InterfaceSetting.i*/
#define RDM_OID_ROUTING_RT_INFO                  66160	/*Device.Routing.RouteInformation*/
#define RDM_OID_ROUTING_RT_INFO_INTF_SET         66296	/*Device.Routing.RouteInformation.InterfaceSetting.i*/
#define RDM_OID_V4_ROUTING_TABLE                 66752	/*Device.Routing.X_ZYXEL_IPV4RoutingTable.i*/
#define RDM_OID_V6_ROUTING_TABLE                 67048	/*Device.Routing.X_ZYXEL_IPV6RoutingTable.i*/
#define RDM_OID_NEIGHBOR_DISCOVERY               67304	/*Device.NeighborDiscovery*/
#define RDM_OID_RT_ADV                           67440	/*Device.RouterAdvertisement*/
#define RDM_OID_RT_ADV_INTF_SET                  67576	/*Device.RouterAdvertisement.InterfaceSetting.i*/
#define RDM_OID_IPV6RD                           68552	/*Device.IPv6rd*/
#define RDM_OID_IPV6RD_INTF                      68688	/*Device.IPv6rd.InterfaceSetting.i*/
#define RDM_OID_DS_LITE                          69184	/*Device.DSLite*/
#define RDM_OID_DS_LITE_INTF_SET                 69320	/*Device.DSLite.InterfaceSetting.i*/
#define RDM_OID_LAN_CONF_SEC                     69896	/*Device.LANConfigSecurity*/
#define RDM_OID_HOSTS                            69992	/*Device.Hosts*/
#define RDM_OID_HOSTS_HOST                       70168	/*Device.Hosts.Host.i*/
#define RDM_OID_HOSTS_HOST_V4_ADDR               71784	/*Device.Hosts.Host.i.IPv4Address.i*/
#define RDM_OID_HOSTS_HOST_V6_ADDR               71880	/*Device.Hosts.Host.i.IPv6Address.i*/
#define RDM_OID_ZY_HOSTS_HOST_EXT                71976	/*Device.Hosts.Host.i.X_ZYXEL_EXT*/
#define RDM_OID_DNS                              72472	/*Device.DNS*/
#define RDM_OID_DNS_CLIENT                       72728	/*Device.DNS.Client*/
#define RDM_OID_DNS_CLIENT_SRV                   72944	/*Device.DNS.Client.Server.i*/
#define RDM_OID_DNS_DIAG                         73440	/*Device.DNS.Diagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG          73496	/*Device.DNS.Diagnostics.NSLookupDiagnostics*/
#define RDM_OID_DNS_DIAG_NS_LOOKUP_DIAG_RESULT   73912	/*Device.DNS.Diagnostics.NSLookupDiagnostics.Result.i*/
#define RDM_OID_NAT                              74208	/*Device.NAT*/
#define RDM_OID_NAT_INTF_SETTING                 74664	/*Device.NAT.InterfaceSetting.i*/
#define RDM_OID_NAT_PORT_MAPPING                 74920	/*Device.NAT.PortMapping.i*/
#define RDM_OID_NAT_PORT_TRIGGERING              75896	/*Device.NAT.X_ZYXEL_PortTriggering.i*/
#define RDM_OID_NAT_ADDR_MAPPING                 76432	/*Device.NAT.X_ZYXEL_AddrMapping.i*/
#define RDM_OID_NAT_SESSION_CTL                  76968	/*Device.NAT.X_ZYXEL_SessionControl*/
#define RDM_OID_DHCPV4                           77344	/*Device.DHCPv4*/
#define RDM_OID_DHCPV4_CLIENT                    77440	/*Device.DHCPv4.Client.i*/
#define RDM_OID_DHCPV4_SENT_OPT                  78336	/*Device.DHCPv4.Client.i.SentOption.i*/
#define RDM_OID_DHCPV4_REQ_OPT                   78552	/*Device.DHCPv4.Client.i.ReqOption.i*/
#define RDM_OID_DHCPV4_SRV                       78808	/*Device.DHCPv4.Server*/
#define RDM_OID_DHCPV4_SRV_POOL                  78984	/*Device.DHCPv4.Server.Pool.i*/
#define RDM_OID_DHCPV4_SRV_POOL_STATIC_ADDR      80400	/*Device.DHCPv4.Server.Pool.i.StaticAddress.i*/
#define RDM_OID_DHCPV4_SRV_POOL_OPT              80616	/*Device.DHCPv4.Server.Pool.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT           80872	/*Device.DHCPv4.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_V4_ADDR   81128	/*Device.DHCPv4.Server.Pool.i.Client.i.IPv4Address.i*/
#define RDM_OID_DHCPV4_SRV_POOL_CLIENT_OPT       81264	/*Device.DHCPv4.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV4_SRV_SUBNET                81400	/*Device.DHCPv4.Server.X_ZYXEL_Subnet.i*/
#define RDM_OID_DHCPV4_RELAY                     81696	/*Device.DHCPv4.Relay*/
#define RDM_OID_DHCPV4_RELAY_FWD                 81912	/*Device.DHCPv4.Relay.Forwarding.i*/
#define RDM_OID_DHCPV6                           82648	/*Device.DHCPv6*/
#define RDM_OID_DHCPV6_CLIENT                    82744	/*Device.DHCPv6.Client.i*/
#define RDM_OID_DHCPV6_CLIENT_SRV                83520	/*Device.DHCPv6.Client.i.Server.i*/
#define RDM_OID_DHCPV6_CLIENT_SENT_OPT           83696	/*Device.DHCPv6.Client.i.SentOption.i*/
#define RDM_OID_DHCPV6_CLIENT_RECEIVED_OPT       83912	/*Device.DHCPv6.Client.i.ReceivedOption.i*/
#define RDM_OID_DHCPV6_SRV                       84088	/*Device.DHCPv6.Server*/
#define RDM_OID_DHCPV6_SRV_POOL                  84224	/*Device.DHCPv6.Server.Pool.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT           85480	/*Device.DHCPv6.Server.Pool.i.Client.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_ADDR   85776	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Address.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_V6_PREFIX 85952	/*Device.DHCPv6.Server.Pool.i.Client.i.IPv6Prefix.i*/
#define RDM_OID_DHCPV6_SRV_POOL_CLIENT_OPT       86128	/*Device.DHCPv6.Server.Pool.i.Client.i.Option.i*/
#define RDM_OID_DHCPV6_SRV_POOL_OPT              86264	/*Device.DHCPv6.Server.Pool.i.Option.i*/
#define RDM_OID_IEEE8021X                        86520	/*Device.IEEE8021x*/
#define RDM_OID_IEEE8021X_SUPPLICANT             86616	/*Device.IEEE8021x.Supplicant.i*/
#define RDM_OID_IEEE8021X_SUPPLICANT_STAT        87392	/*Device.IEEE8021x.Supplicant.i.Stats*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPMD5      87888	/*Device.IEEE8021x.Supplicant.i.EAPMD5*/
#define RDM_OID_IEEE8021X_SUPPLICANT_EAPTLS      88024	/*Device.IEEE8021x.Supplicant.i.EAPTLS*/
#define RDM_OID_USRS                             88160	/*Device.Users*/
#define RDM_OID_USRS_USR                         88256	/*Device.Users.User.i*/
#define RDM_OID_SELF_TEST_DIAG                   88552	/*Device.SelfTestDiagnostics*/
#define RDM_OID_FIREWALL                         88688	/*Device.Firewall*/
#define RDM_OID_FIREWALL_LEVEL                   89224	/*Device.Firewall.Level.i*/
#define RDM_OID_FIREWALL_CHAIN                   89640	/*Device.Firewall.Chain.i*/
#define RDM_OID_FIREWALL_CHAIN_RULE              89896	/*Device.Firewall.Chain.i.Rule.i*/
#define RDM_OID_DEV_SEC                          91752	/*Device.Security*/
#define RDM_OID_DEV_SEC_CERT                     91848	/*Device.Security.Certificate.i*/
#define RDM_OID_ROM_CONVERT                      92624	/*Device.X_ZYXEL_RomConvert.i*/
#define RDM_OID_EMAIL_NOTIFY                     92720	/*Device.X_ZYXEL_EmailNotification*/
#define RDM_OID_MAIL_SERVICE                     92776	/*Device.X_ZYXEL_EmailNotification.EmailService.i*/
#define RDM_OID_MAIL_EVENT_CFG                   93152	/*Device.X_ZYXEL_EmailNotification.EmailEventConfig.i*/
#define RDM_OID_PAREN_CTL                        93448	/*Device.X_ZYXEL_ParentalControl*/
#define RDM_OID_PAREN_CTL_PROF                   93544	/*Device.X_ZYXEL_ParentalControl.Profile.i*/
#define RDM_OID_IEEE8021AG                       94160	/*Device.X_ZYXEL_8021ag*/
#define RDM_OID_IEEE8023AH                       94976	/*Device.X_ZYXEL_8023ah*/
#define RDM_OID_ZY_EXT                           95392	/*Device.X_ZYXEL_EXT*/
#define RDM_OID_DNS_RT_ENTRY                     95688	/*Device.X_ZYXEL_EXT.DNSRouteEntry.i*/
#define RDM_OID_DNS_ENTRY                        96104	/*Device.X_ZYXEL_EXT.DNSEntry.i*/
#define RDM_OID_D_DNS                            96240	/*Device.X_ZYXEL_EXT.DynamicDNS*/
#define RDM_OID_AUTO_PROV                        96936	/*Device.X_ZYXEL_EXT.AutoProvision*/
#define RDM_OID_ZY_HOST_NAME_REPLACE             97312	/*Device.X_ZYXEL_EXT.HostNameReplace*/
#define RDM_OID_VPN_CFG                          97408	/*Device.X_ZYXEL_EXT.X_ZYXEL_VPN*/
#define RDM_OID_VPN_CLIENT_CFG                   97504	/*Device.X_ZYXEL_EXT.X_ZYXEL_VPN.X_ZYXEL_VPNClient_Config.i*/
#define RDM_OID_EOGRE_CFG                        98080	/*Device.X_ZYXEL_EXT.X_ZYXEL_EoGRE_Config*/
#define RDM_OID_LAN_DEV                          98376	/*Device.X_ZYXEL_EXT.LANDevice.i*/
#define RDM_OID_DATA_ELEMENT                     98552	/*Device.X_ZYXEL_EXT.DataElement*/
#define RDM_OID_MAC_ADDRESS_TABLE                98648	/*Device.X_ZYXEL_EXT.MacAddressTable*/
#define RDM_OID_LINK_QUALITY                     98984	/*Device.X_ZYXEL_EXT.LinkQuality*/
#define RDM_OID_EASY_MESH                        99160	/*Device.X_ZYXEL_EXT.EasyMesh*/
#define RDM_OID_EASY_MESH_TS                     99496	/*Device.X_ZYXEL_EXT.EasyMesh.EasyMeshTs*/
#define RDM_OID_WPS_BUTTON_PRESS                 99672	/*Device.X_ZYXEL_EXT.WpsButtonPress*/
#define RDM_OID_ZY_IGMP                          99888	/*Device.X_ZYXEL_IGMP*/
#define RDM_OID_ZY_IGMP_D_ACL                    100744	/*Device.X_ZYXEL_IGMP.DynamicACLTable.i*/
#define RDM_OID_DEV_SNOOP_TABLE                  100920	/*Device.X_ZYXEL_IGMP.SNOOP_TABLE.i*/
#define RDM_OID_DEV_MCST_TABLE                   101176	/*Device.X_ZYXEL_IGMP.MCAST_TABLE.i*/
#define RDM_OID_ZY_MLD                           101352	/*Device.X_ZYXEL_MLD*/
#define RDM_OID_ZY_LOG_CFG                       102048	/*Device.X_ZYXEL_LoginCfg*/
#define RDM_OID_ZY_LOG_CFG_GP                    102264	/*Device.X_ZYXEL_LoginCfg.LogGp.i*/
#define RDM_OID_ZY_LOG_CFG_GP_ACCOUNT            102560	/*Device.X_ZYXEL_LoginCfg.LogGp.i.Account.i*/
#define RDM_OID_ZY_MAC_FILTER                    104016	/*Device.X_ZYXEL_MacFilter*/
#define RDM_OID_ZY_MAC_FILTER_WHITE_LIST         104192	/*Device.X_ZYXEL_MacFilter.WhiteList.i*/
#define RDM_OID_ZY_IP_FILTER                     104368	/*Device.X_ZYXEL_IpFilter*/
#define RDM_OID_ZY_IP_FILTER_WHITE_LIST          104544	/*Device.X_ZYXEL_IpFilter.WhiteList.i*/
#define RDM_OID_VLAN_AUTO_HUNT                   104720	/*Device.X_ZYXEL_VlanAutoHunt*/
#define RDM_OID_VLAN_HUNT_INFO                   104936	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i*/
#define RDM_OID_VLAN_HUNT_RULE                   105072	/*Device.X_ZYXEL_VlanAutoHunt.VlanHuntInfo.i.VlanHuntRule.i*/
#define RDM_OID_LANG                             105208	/*Device.X_ZYXEL_Language*/
#define RDM_OID_REMO_MGMT                        105304	/*Device.X_ZYXEL_RemoteManagement*/
#define RDM_OID_REMO_SRV                         105600	/*Device.X_ZYXEL_RemoteManagement.Service.i*/
#define RDM_OID_REMO_SRV_TRUST_DOMAIN            106136	/*Device.X_ZYXEL_RemoteManagement.Service.i.TrustDomain.i*/
#define RDM_OID_SP_REMO_SRV                      106312	/*Device.X_ZYXEL_RemoteManagement.SPService.i*/
#define RDM_OID_SP_REMO_SRV_TRUST_DOMAIN         106808	/*Device.X_ZYXEL_RemoteManagement.SPService.i.TrustDomain.i*/
#define RDM_OID_REMO_MGMT_TRUST_DOMAIN           107024	/*Device.X_ZYXEL_RemoteManagement.TrustDomain.i*/
#define RDM_OID_SP_TRUST_DOMAIN                  107200	/*Device.X_ZYXEL_RemoteManagement.SPTrustDomain.i*/
#define RDM_OID_INTERFACE_TRUST_DOMAIN           107416	/*Device.X_ZYXEL_RemoteManagement.InterfaceTrustDomain.i*/
#define RDM_OID_INTERFACE_TRUST_DOMAIN_INFO      107552	/*Device.X_ZYXEL_RemoteManagement.InterfaceTrustDomain.i.TrustDomainInfo.i*/
#define RDM_OID_M_PRO_MESH_APP                   107728	/*Device.X_ZYXEL_RemoteManagement.MProMeshApp*/
#define RDM_OID_NETWORK_SRV                      107824	/*Device.X_ZYXEL_NetworkService*/
#define RDM_OID_NETWORK_SRV_GP                   107920	/*Device.X_ZYXEL_NetworkService.Service.i*/
#define RDM_OID_SYSTEM_INFO                      108336	/*Device.X_ZYXEL_System_Info*/
#define RDM_OID_LOG_SETTING                      108792	/*Device.X_ZYXEL_Log_Setting*/
#define RDM_OID_LOG_CLASSIFY                     109208	/*Device.X_ZYXEL_Log_Setting.LogClassify.i*/
#define RDM_OID_LOG_CATEGORY                     109424	/*Device.X_ZYXEL_Log_Setting.LogClassify.i.Category.i*/
#define RDM_OID_CHANGE_ICON_NAME                 109720	/*Device.X_ZYXEL_Change_Icon_Name.i*/
#define RDM_OID_PORT_MIRROR                      110376	/*Device.X_ZYXEL_PortMirroring.i*/
#define RDM_OID_TR064                            110712	/*Device.X_ZYXEL_TR064*/
#define RDM_OID_ACL                              111008	/*Device.X_ZYXEL_TR064.ACL*/
#define RDM_OID_CONTROL_POINT                    111064	/*Device.X_ZYXEL_TR064.ACL.CP.i*/
#define RDM_OID_ACTIONS                          111280	/*Device.X_ZYXEL_TR064.ACL.Actions.i*/
#define RDM_OID_GUI_CUSTOMIZATION                111456	/*Device.X_ZYXEL_GUI_CUSTOMIZATION*/
#define RDM_OID_INPUT_CHECK_LIST                 112272	/*Device.X_ZYXEL_GUI_CUSTOMIZATION.InputCheckList.i*/
#define RDM_OID_FEATURE_FLAG                     112568	/*Device.X_ZYXEL_FEATRUE_FLAG*/
#define RDM_OID_INIT_FLAG                        113664	/*Device.X_ZYXEL_INIT_FLAG*/
#define RDM_OID_ZY_OPTION125                     113800	/*Device.X_ZYXEL_Option125VendorSpecific*/
#define RDM_OID_ZY_VENDOR_SPECIFIC               113896	/*Device.X_ZYXEL_Option125VendorSpecific.VendorSpecific.i*/
#define RDM_OID_INTERNAL_DATA                    114112	/*Device.X_ZYXEL_InternalData*/
#define RDM_OID_ONLINE_F_W_UPGRADE               114208	/*Device.X_ZYXEL_Online_FW_Upgrade*/
#define RDM_OID_LANDING_PAGE                     114624	/*Device.X_ZYXEL_Landing_Page*/
#define RDM_OID_ZY_RESET_ADMIN                   114760	/*Device.X_ZYXEL_RESET_ADMIN*/
#define RDM_OID_CRONTAB                          114856	/*Device.X_ZYXEL_Crontab*/
#define RDM_OID_IPERF                            114952	/*Device.X_ZYXEL_Iperf*/
#define RDM_OID_CONTENT_FILTER                   115168	/*Device.X_ZYXEL_ContentFilter.i*/
#define RDM_OID_SYSTEM_DEBUG                     115984	/*Device.X_ZYXEL_System_Debug*/
#define RDM_OID_POWER_MGMT                       116240	/*Device.X_ZYXEL_Power_Management*/
#define RDM_OID_POWER_SCHEDULE                   116936	/*Device.X_ZYXEL_Power_Management.PowerSchedule.i*/
#define RDM_OID_ZY_SNMP                          117192	/*Device.X_ZYXEL_SNMP*/
#define RDM_OID_TRAP_ADDR                        117448	/*Device.X_ZYXEL_SNMP.TrapAddr.i*/
#define RDM_OID_WIFI                             117624	/*Device.WiFi*/
#define RDM_OID_WIFI_ONE_SSID                    118000	/*Device.WiFi.X_ZYXEL_OneSSID*/
#define RDM_OID_WIFI_RADIO                       118096	/*Device.WiFi.Radio.i*/
#define RDM_OID_WIFI_RADIO_ST                    121152	/*Device.WiFi.Radio.i.Stats*/
#define RDM_OID_WIFI_SSID                        121568	/*Device.WiFi.SSID.i*/
#define RDM_OID_WIFI_SSID_STAT                   122864	/*Device.WiFi.SSID.i.Stats*/
#define RDM_OID_WIFI_ACCESS_POINT                123560	/*Device.WiFi.AccessPoint.i*/
#define RDM_OID_WIFI_ACCESS_POINT_SEC            124176	/*Device.WiFi.AccessPoint.i.Security*/
#define RDM_OID_WIFI_ACCESS_POINT_ACCOUNTING     126032	/*Device.WiFi.AccessPoint.i.Accounting*/
#define RDM_OID_WIFI_ACCESS_POINT_WPS            126408	/*Device.WiFi.AccessPoint.i.WPS*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV      127224	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_ACCESS_POINT_ASSOC_DEV_ST   127720	/*Device.WiFi.AccessPoint.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_STA_FILTER                  128136	/*Device.WiFi.AccessPoint.i.StationFilter*/
#define RDM_OID_WIFI_DIAGNOSTIC                  128312	/*Device.WiFi.NeighboringWiFiDiagnostic*/
#define RDM_OID_WIFI_DIAGNOSTIC_RESULTS          128488	/*Device.WiFi.NeighboringWiFiDiagnostic.Result.i*/
#define RDM_OID_WIFI_MAP                         129344	/*Device.WiFi.MultiAP*/
#define RDM_OID_WIFI_MAP_STEERING_SUM_ST         129440	/*Device.WiFi.MultiAP.SteeringSummaryStats*/
#define RDM_OID_WIFI_MAP_APDEV                   129816	/*Device.WiFi.MultiAP.APDevice.i*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO             130472	/*Device.WiFi.MultiAP.APDevice.i.Radio.i*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP          130888	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP_ASSOCDEV 131184	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i.AssociatedDevice.i*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP_ASSOCDEV_ST 131600	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i.AssociatedDevice.i.Stats*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP_ASSOCDEV_STEERING_SUM_ST 131936	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i.AssociatedDevice.i.SteeringSummaryStats*/
#define RDM_OID_WIFI_MAP_APDEV_RADIO_AP_ASSOCDEV_STEERING_HISTORY 132352	/*Device.WiFi.MultiAP.APDevice.i.Radio.i.AP.i.AssociatedDevice.i.SteeringHistory.i*/
#define RDM_OID_QOS                              132648	/*Device.QoS*/
#define RDM_OID_QOS_CLS                          133744	/*Device.QoS.Classification.i*/
#define RDM_OID_QOS_APP                          137280	/*Device.QoS.App.i*/
#define RDM_OID_QOS_FLOW                         137736	/*Device.QoS.Flow.i*/
#define RDM_OID_QOS_POLICER                      138272	/*Device.QoS.Policer.i*/
#define RDM_OID_QOS_QUE                          139208	/*Device.QoS.Queue.i*/
#define RDM_OID_QOS_QUE_STAT                     140104	/*Device.QoS.QueueStats.i*/
#define RDM_OID_QOS_SHAPER                       140600	/*Device.QoS.Shaper.i*/
#define RDM_OID_SCHEDULE                         140896	/*Device.X_ZYXEL_Schedule.i*/
#define RDM_OID_ZY_W_W_A_N_BACKUP                141392	/*Device.X_ZYXEL_WWAN_BACKUP*/
#define RDM_OID_ZY_W_W_A_N_PING_CHECK            142168	/*Device.X_ZYXEL_WWAN_BACKUP.PingCheck*/
#define RDM_OID_ZY_W_W_A_N_BUDGET_CONTROL        142504	/*Device.X_ZYXEL_WWAN_BACKUP.BudgetControl*/
#define RDM_OID_ZY_W_W_A_N_STAT                  143640	/*Device.X_ZYXEL_WWAN_BACKUP.Stats*/
#define RDM_OID_HOME_CYBER_SECURITY              144296	/*Device.X_ZYXEL_HomeCyberSecurity*/
#define RDM_OID_DEV_INFO                         144552	/*Device.DeviceInfo*/
#define RDM_OID_DEV_INFO_VEND_CONF_FILE          145688	/*Device.DeviceInfo.VendorConfigFile.i*/
#define RDM_OID_DEV_INFO_SUP_DATA_MODEL          145944	/*Device.DeviceInfo.SupportedDataModel.i*/
#define RDM_OID_DEV_INFO_MEM_STAT                146160	/*Device.DeviceInfo.MemoryStatus*/
#define RDM_OID_DEV_INFO_PS_STAT                 146296	/*Device.DeviceInfo.ProcessStatus*/
#define RDM_OID_DEV_INFO_PS_STAT_PS              146432	/*Device.DeviceInfo.ProcessStatus.Process.i*/
#define RDM_OID_TEMP_STAT                        146728	/*Device.DeviceInfo.TemperatureStatus*/
#define RDM_OID_TEMP_STAT_TEMP_SENSOR            146824	/*Device.DeviceInfo.TemperatureStatus.TemperatureSensor.i*/
#define RDM_OID_NETWORK_PROP                     147560	/*Device.DeviceInfo.NetworkProperties.i*/
#define RDM_OID_DEV_INFO_PROCESSOR               147696	/*Device.DeviceInfo.Processor.i*/
#define RDM_OID_DEV_INFO_VENDOR_LOG_FILE         147832	/*Device.DeviceInfo.VendorLogFile.i*/
#define RDM_OID_DEV_INFO_PROXIER_INFO            148048	/*Device.DeviceInfo.ProxierInfo.i*/
#define RDM_OID_DEV_INFO_LOC                     148264	/*Device.DeviceInfo.Location.i*/
#define RDM_OID_DEV_INFO_POWER_STAT              148520	/*Device.DeviceInfo.X_ZYXEL_PowerStatus*/
#define RDM_OID_USB                              148656	/*Device.USB*/
#define RDM_OID_USB_INTF                         148792	/*Device.USB.Interface.i*/
#define RDM_OID_USB_INTF_STAT                    149288	/*Device.USB.Interface.i.Stats*/
#define RDM_OID_USB_PORT                         149944	/*Device.USB.Port.i*/
#define RDM_OID_USB_USBHOSTS                     150320	/*Device.USB.USBHosts*/
#define RDM_OID_USB_USBHOSTS_HOST                150416	/*Device.USB.USBHosts.Host.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV            150792	/*Device.USB.USBHosts.Host.i.Device.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_PAR        151648	/*Device.USB.USBHosts.Host.i.Device.i.X_ZYXEL_Partition.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG        151904	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i*/
#define RDM_OID_USB_USBHOSTS_HOST_DEV_CFG_INTF   152040	/*Device.USB.USBHosts.Host.i.Device.i.Configuration.i.Interface.i*/
#define RDM_OID_U_R_L_FILTER                     152256	/*Device.X_ZYXEL_URLFilter.i*/
#define RDM_OID_WHITE_U_R_L_FILTER               152472	/*Device.X_ZYXEL_URLFilter.i.WhiteList.i*/
#define RDM_OID_BLACK_U_R_L_FILTER               152648	/*Device.X_ZYXEL_URLFilter.i.BlackList.i*/
#define RDM_OID_VLAN_GROUP                       152824	/*Device.X_ZYXEL_VlanGroup.i*/
#define RDM_OID_SPEED_TEST                       153120	/*Device.SpeedTestInfo*/
#define RDM_OID_T_F_T_P_SRV_NAME                 153416	/*Device.X_ZYXEL_TFTP_SERVER_NAME*/
#define RDM_OID_SW_MODULE                        153512	/*Device.SoftwareModules*/
#define RDM_OID_SW_MODULE_EE_CONF                153688	/*Device.SoftwareModules.X_ZYXEL_ExecEnvConfigure*/
#define RDM_OID_SW_MODULE_EXEC_ENV               153864	/*Device.SoftwareModules.ExecEnv.i*/
#define RDM_OID_SW_MODULE_DEPLOYMENT_UNIT        154720	/*Device.SoftwareModules.DeploymentUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT              155336	/*Device.SoftwareModules.ExecutionUnit.i*/
#define RDM_OID_SW_MODULE_EXEC_UNIT_EXTENSIONS   156232	/*Device.SoftwareModules.ExecutionUnit.i.Extensions*/
#define RDM_OID_ZLOG_CONFIG                      156368	/*Device.X_ZYXEL_Zlog_Setting*/
#define RDM_OID_ZLOG_CATEGORY                    156504	/*Device.X_ZYXEL_Zlog_Setting.ZlogCategory.i*/
#define RDM_OID_DLNA                             157080	/*Device.DLNA*/
#define RDM_OID_DLNA_CAPB                        157376	/*Device.DLNA.Capabilities*/
#define RDM_OID_ZY_ONE_CONNECT                   157752	/*Device.X_ZYXEL_OneConnect*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_MASTER_SWITCH 158088	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter*/
#define RDM_OID_ONE_CONNECT_INTERNET_ACCESS_RULE 158224	/*Device.X_ZYXEL_OneConnect_Internet_Access_Filter.Rule.i*/
#define RDM_OID_ZY_LICNSE                        158440	/*Device.X_ZYXEL_License*/
#define RDM_OID_XMPP                             158616	/*Device.XMPP*/
#define RDM_OID_XMPP_CONN                        158752	/*Device.XMPP.Connection.i*/
#define RDM_OID_XMPP_CONN_SRV                    159368	/*Device.XMPP.Connection.i.Server.i*/
#define RDM_OID_UPNP                             159664	/*Device.UPnP*/
#define RDM_OID_UPNP_DEV                         159720	/*Device.UPnP.Device*/
#define RDM_OID_UPNP_DEV_CAPB                    160256	/*Device.UPnP.Device.Capabilities*/
#define RDM_OID_UPNP_DISC                        160792	/*Device.UPnP.Discovery*/
#define RDM_OID_UPNP_DISC_ROOT_DEV               160968	/*Device.UPnP.Discovery.RootDevice.i*/
#define RDM_OID_UPNP_DISC_DEV                    161304	/*Device.UPnP.Discovery.Device.i*/
#define RDM_OID_UPNP_DISC_SERVICE                161640	/*Device.UPnP.Discovery.Service.i*/
#define RDM_OID_ZY_SAMBA                         161936	/*Device.X_ZYXEL_SAMBA*/
#define RDM_OID_ZY_SAMBA_DIR                     162192	/*Device.X_ZYXEL_SAMBA.Directory.i*/
#define RDM_OID_ZY_DATA_USAGE                    162608	/*Device.X_ZYXEL_DataUsage*/
#define RDM_OID_ZY_DATA_USAGE_LAN                162704	/*Device.X_ZYXEL_DataUsage.Lan.i*/
#define RDM_OID_ZY_DATA_USAGE_WAN                162880	/*Device.X_ZYXEL_DataUsage.Wan.i*/
#define RDM_OID_S_T_B_VENDOR_I_D                 163056	/*Device.X_ZYXEL_STB_VENDOR_ID*/
#define RDM_OID_LIFEMOTE_AGENT                   163312	/*Device.X_ZYXEL_LifeMoteAgent*/

#define RDM_OID_MAX                   163488     // for OID validation

#define RDM_OID_IS_INVALID(_oid_)    ((_oid_ < 0) || (_oid_ >= RDM_OID_MAX))

#endif // _ZCFG_RDM_OID_H
